### ISSUE TITLE
CLASS SMTP NOT FOUND

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#100]
Fatal error: Class 'SMTP' not found in /home/admin/web/xterium.space/public_html/includes/libs/phpmailer/class.phpmailer.php on line 1443

When i try to use the smtp function in admin panel and after that try to register an account

**Comment by tatarysh** [comment]
in file, line 28: includes/libs/phpmailer/class.phpmailer.php

paste:
require 'includes/libs/phpmailer/class.smtp.php';

**Comment by Hilarious001** [comment]
Already did that before but this make load the page forever when some one register
Using google webdeveloper apps as email domain.

**Comment by tatarysh** [comment]
I'm sorry, but I do not understand you now.

**Comment by jkroepke** [comment]
Is this still valid?

**Comment by Hilarious001** [comment]
can be closed
