### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#116]
Hello jan

Is there any difference in the french language pack of 1.7.3 and pdo version
Do you still have a checker that can tell me the missing language vars?

Regards

**Comment by jkroepke** [comment]
Currently no. I will try http://pootle.translatehouse.org/ so maybe it will be easier for all.

**Comment by Hilarious001** [comment]
Ok no problem
i am making it in french and dutch
send me an email where i can send once finished

**Comment by jkroepke** [comment]
For me: Also https://weblate.org/de/ should be an option.

**Comment by Hilarious001** [comment]
both would be nice, i will send you the official french pack this weekend so you can add it on your main pack to

I used the main english files to do it so normaly all lines should be included.

Regards

**Comment by jkroepke** [comment]
I'm testing weblate now: http://weblate.creativesandbox.de/projects/2moons/banner/

**Comment by Hilarious001** [comment]
Closed let us know when possible to help

**Comment by jkroepke** [comment]
Hi!

i was think you send it via mail.

Cheers,
Jan
