### ISSUE TITLE
error while accessing administration

### ISSUE THREAD

**Issue by d3tr0l** [jkroepke/2Moons#119]
when clicking on administration(1.8.git) button ingame, for opening admin feature panels etc. this error is thrown up:

Message: Undefined variable: USER
File: /admin.php
Line: 37
URL: http://localhost/2moons/admin.php
PHP-Version: 5.6.15
PHP-API: apache2handler
MySQL-Cleint-Version: mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
2Moons Version: 1.8.git
Debug Backtrace:
#0 /admin.php(37): errorHandler(8, 'Undefined varia...', 'C://xampp//htdocs...', 37, Array)
#1 {main} 

already discussed on forum with one member, i do not know where the fault is, i just downloaded the master branch from here and installed. using PDO(as it is already inregrated), running on xampp. same error on wamp.

**Comment by d3tr0l** [comment]
for anyone having this issue, get older php version, because the 5.6 does not support this.

**Comment by jkroepke** [comment]
Really? I run 2Moons with PHP 5.6, also with PHP7 and do not have errors like this...

**Comment by jkroepke** [comment]
From http://2moons.cc/index.php?thread/8991-error-in-admin-php-help-please/&postID=65418#post65418 I can use you are using a old version.

Fixed in https://github.com/jkroepke/2Moons/commit/2c6a79c0c04e3084fd0a3ddef76e5fd94539fb07
