### ISSUE TITLE
Problem in admin panel -> Server Configuration

### ISSUE THREAD

**Issue by FrancisLeRoy** [jkroepke/2Moons#121]
If i try to click on "Save" button in Server Configuration page, it redirect to hosting provider homepage.
How is it possible?

**Comment by tatarysh** [comment]
Use Xdebug : http://wiki.netbeans.org/HowToConfigureXDebug

**Comment by jkroepke** [comment]
I think XDebug should not work on a public hoster.

**Comment by tatarysh** [comment]
Check on the local machine, if you had the same problem you have an error in the files - then use xdebug.

**Comment by FrancisLeRoy** [comment]
But, you have not this problem?

**Comment by jkroepke** [comment]
Personally I think your provider has some restrictions. There is no feature in the game that you can redirect to your hoster.
