### ISSUE TITLE
Impossible to register a new player

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#122]
Debug Backtrace:
#0 /includes/classes/PlayerUtil.class.php(165): errorHandler(8, 'Undefined index...', 'FILEPATH ...', 165, Array)
#1 /includes/pages/login/ShowVertifyPage.class.php(72): PlayerUtil::createPlayer('1', 'Casandro', '$2a$09$ybkaGvQq...', 'moellerdaniel@t...', 'de')
#2 /includes/pages/login/ShowVertifyPage.class.php(140): ShowVertifyPage->_activeUser()
#3 /index.php(68): ShowVertifyPage->show()
#4 {main}

**Comment by bergi9** [comment]
Update your code from github again, there was a fix some time ago. (147eac47276d3fcf531a59835019a735e33a0b8c and 6a4467ebb513ef7204a6a947ec8af65a72cc993d)

**Comment by Hilarious001** [comment]
Closed
