### ISSUE TITLE
Question before pulling

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#128]
hello i dont want to pull an error for nothing but basicly isnt this an error in mission case attack +- line 142?

$sql	= "SELECT * FROM %%USERS%% WHERE id = :userId;";
$fleetDefend[$fleetID]['player']			= $db->selectSingle($sql, array(
':userId'	=> $fleetDetail['fleet_owner']
));

Shouldnt fleet_owner not be fleet_target_owner for $fleetDefend ?

Regards

**Comment by jkroepke** [comment]
https://github.com/jkroepke/2Moons/blob/master/includes/classes/missions/MissionCaseAttack.class.php#L142

No. you query the owner of the hold fleets to collect technology.

**Comment by Hilarious001** [comment]
Thanks all i wanted to know

Regards
