### ISSUE TITLE
Multi connexion

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#136]
Hello jan, i have a small question, i noticed that since i use the pdo version, that you are not able to log in on another computer if you have already a open window of the game on another device,

Example, i am logged home and have to go to work, i forgot to close the window at my home computer and now when i login on my work computer i get after a few seconds session expired until i close the window at home; is this due to a code of yours, or is it possible that is log a user of if a js file continue to call an url to check if you have message. i have no idea what message i can have at home nor if i m still logged after all there.

It doesnt change if i destroy all sessions in db. i really need to close the window

Regards

**Comment by lilmnm-kamikaze-** [comment]
https://github.com/jkroepke/2Moons/blob/master/includes/classes/Session.class.php#L255

the session class checks the ip of the user and if it sees two ips for the same user the isValidSession() function is returned false and that makes the session expire.

**Comment by Hilarious001** [comment]
Thanks
