### ISSUE TITLE
Buildlist Gebäude in der Warteschlange

### ISSUE THREAD

**Issue by Gobisan2000** [jkroepke/2Moons#139]
Hey was muss ich ändern damit die Ressorcen für die Gebäude in der Warteschlange direkt abgezogen werden?

**Comment by jkroepke** [comment]
Du müsstest grundlegende Teile Warteschlange umschreiben.

[Dort](https://github.com/jkroepke/2Moons/blob/9462e187a804b65fde0b8cf38c874db1de242d9c/includes/pages/game/ShowBuildingsPage.class.php#L151-L197) z.b. die Abfrage entfernen und den Code universell für beide Fälle anpassen.

Dann müsstest du noch dafür sorgen, dass beim Abbrechen der Bauschleife noch Ressource zurückgegeben werden. Dazu müsstest du den Funktionen [hier](https://github.com/jkroepke/2Moons/blob/9462e187a804b65fde0b8cf38c874db1de242d9c/includes/pages/game/ShowBuildingsPage.class.php#L27-L114) vereinheitlichen.

Zu guter Letzt noch die Ressourcenlogik aus der Warteschlange selbst entfernen:

https://github.com/jkroepke/2Moons/blob/a7294be3cb92b998479460f78e8540cf0a45fe42/includes/classes/class.PlanetRessUpdate.php#L457-L478

**Comment by Gobisan2000** [comment]
Ok danke leider bin ich noch absoluter neuling im Coden wenn mir das einer machen würde wäre ich sehr dankbar :)

**Comment by jkroepke** [comment]
Das wäre in einem Forum besser aufgehoben, als im Bugtracker.
