### ISSUE TITLE
Would you consider adding some mods from the forum to default 2moons?

### ISSUE THREAD

**Issue by OzanKurt** [jkroepke/2Moons#141]
Would you consider adding some mods from the forum to default 2moons?

**Comment by Hilarious001** [comment]
i dont think he will since i think he want to be the closest as possible then the real ogame

**Comment by ogamemaster** [comment]
super ok

**Comment by jkroepke** [comment]
If the code quality is good enough and its a useful mod for a space game, yes.

For example: A Lottery is in my opinion not a useful mod. An 3d galaxy viewer, too.

**Comment by OzanKurt** [comment]
So do you have something in mind?

**Comment by jkroepke** [comment]
Nope.
