### ISSUE TITLE
Session active-error!!!

### ISSUE THREAD

**Issue by ogamemaster** [jkroepke/2Moons#143]
I am logged in to game 
localhost/game.php  is ok
but
localhost/ not replaced to localhost/game.php ,i see only the login page 

How to fix it?
Sorry my bad english

**Comment by Hilarious001** [comment]
you will not see the game page accesing localhost/ but rather the index;php xD

**Comment by ogamemaster** [comment]
I am logged into game ,but the home page localhost/  not redirect to the game.php page 
how to fix ,to thegame use cookies !

**Comment by Hilarious001** [comment]
lol you know you can change cookie values and thus acces the admin account ?? :p
