### ISSUE TITLE
Search not work

### ISSUE THREAD

**Issue by gpcore** [jkroepke/2Moons#145]
Hi, we have not working search. In alliance tab search not work too.

**Comment by Hilarious001** [comment]
Read the commits and pull requests

**Comment by gpcore** [comment]
What you mean? i am use last version.

**Comment by BassXX** [comment]
Hey, I have the same problem over here. I have the newest version of the ShowSearchPage.php

**Comment by BassXX** [comment]
Works Perfekt! Thank you very much!

**Comment by BassXX** [comment]
Hey Guys, thanks for the help! Search is now working for Planets & Players, but unfortunately not for Allies :(

Is there a possibility to fix this?

**Comment by Hilarious001** [comment]
open another issue

**Comment by Hilarious001** [comment]
can this be closed then
Regards
