### ISSUE TITLE
Need Online

### ISSUE THREAD

**Issue by gpcore** [jkroepke/2Moons#146]
We can made "show online" players in game right now ? like admin online but more simple for players.

**Comment by OzanKurt** [comment]
Google search "MySQL Beginner Tutorials The New Boston" :D

**Comment by jkroepke** [comment]
Its not a bug.

**Comment by gpcore** [comment]
I am ask you add this function to game mini stats online players like admin online.

**Comment by lilmnm-kamikaze-** [comment]
That would take the skill of hunting your targets out of the game.

Date: Thu, 3 Mar 2016 14:57:32 -0800
