### ISSUE TITLE
How to block expedition?

### ISSUE THREAD

**Issue by gpcore** [jkroepke/2Moons#147]
How i can made to block send spy zond to expedition?

**Comment by jkroepke** [comment]
Its not a bug.

**Comment by gpcore** [comment]
I am ask you how i can block some kinf of ships for expediton?

**Comment by noonn** [comment]
ok.  your a 2moons ver?

**Comment by gpcore** [comment]
Last from this repo. Can you add me in skype - gpcore

**Comment by noonn** [comment]
find in    includes/classes/class.FleetFunctions.php
`
if ($MissionInfo['planet'] == (Config::get('max_planets') + 1) && isModulAvalible(MODULE_MISSION_EXPEDITION))
			$avalibleMissions[]	= 15;
`

Modify (added !isset($MissionInfo['Ship'][210]) )
`
if ($MissionInfo['planet'] == (Config::get('max_planets') + 1) && isModulAvalible(MODULE_MISSION_EXPEDITION)  && !isset($MissionInfo['Ship'][210]))
			$avalibleMissions[]	= 15;
`

You can also add other types of ships.

**Comment by gpcore** [comment]
ty :)
add me to skype please :)

**Comment by noonn** [comment]
Do not use skype. :)
And my English is not very good.
Sorry ;;
