### ISSUE TITLE
Keep getting this error, Jump from account to account sessions

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#149]
Hello nothing really changed since days exept for my vps hosting compagny and i suddently experience for al my players a jump to other players account, where they can do what they want...

[06-Mar-2016 03:49:28 Europe/Brussels] PHP Fatal error:  Uncaught exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'userID' cannot be null<br>
<br>
Query-Code:REPLACE INTO uni1_session SET
		sessionID	= 1ab21af39d2ebcb7e81fedcf18028e58,
		userID		= ,
		lastonline	= 1457232568,
		userIP		= 80.200.59.250;' in /home/xterium/public_html/includes/classes/Database.class.php:109
Stack trace:
#0 /home/xterium/public_html/includes/classes/Database.class.php(152): Database->_query('REPLACE INTO %%...', Array, 'replace')
#1 /home/xterium/public_html/includes/classes/Session.class.php(229): Database->replace('REPLACE INTO %%...', Array)
#2 [internal function]: Session->save()
#3 {main}
  thrown in /home/xterium/public_html/includes/classes/Database.class.php on line 109

**Comment by gpcore** [comment]
You have problem with mysql looks like :) I read your another thread about sql errors.

**Comment by Hilarious001** [comment]
My problem was with cpanel/whm, they dont want to run my game correctly went back to my free vestacp panel and all is back fine

**Comment by OzanKurt** [comment]
It's about table type, it basicly requires a valid id from users table. A typical behaviour of InnoDB for indexing and optimizations. There is probably nothing wrong with WHM.
