### ISSUE TITLE
[Alliance] Cant change member rank

### ISSUE THREAD

**Issue by gpcore** [jkroepke/2Moons#151]
Not work function set another rank to ally member. You can made new rank but cant set it.

**Comment by Hilarious001** [comment]
easy to fix but before you have any basics of php as those little probles are really easy to fix ?

**Comment by jkroepke** [comment]
Is this still valid?

**Comment by BassXX** [comment]
yes. it does not work for me, too. Would be nice to get this fixed

**Comment by bornhaeusser** [comment]
Yes also not working in my installation. Could not Change "Neuling" to anything else....

<img width="791" alt="bildschirmfoto 2016-05-27 um 10 20 33" src="https://cloud.githubusercontent.com/assets/6609040/15602297/bc041598-23f4-11e6-82e1-cf2eadfee925.png">

**Comment by jkroepke** [comment]
Fixed this issue and added more smarter way to save the ranks.
