### ISSUE TITLE
Alliance Tag & Alliance Name Search does not work

### ISSUE THREAD

**Issue by BassXX** [jkroepke/2Moons#154]
Hello guys, just want to inform you, that the Alliance Tag and Name is not working for me. Player and Planet Search is working fine for me.

Hope we can fix that soon! Thank you guys!

**Comment by BassXX** [comment]
Hey, I have changed the coden (2 line insertions, 1 line removal) in ShowAlliancePage.class.php, but unfortunately the search is still giving me no results :(

**Comment by lilmnm-kamikaze-** [comment]
Is there any kind of error that's being displayed or does it just not do anything?

Date: Tue, 15 Mar 2016 03:58:54 -0700

**Comment by BassXX** [comment]
Hey there,

No error at all, it just displays no results, although allies are existing

**Comment by Hilarious001** [comment]
can you try updated the file

**Comment by BassXX** [comment]
Greetings Hilarious001,

I just modified the file, but still get an empty result when performing the search. 

Thank you guys for trying to help me out. Hopefully we can fix this

**Comment by Hilarious001** [comment]
its working for me so i probably changed somethin else on the alliance page i will look when i am home so i can give you all modification or add me skype xterium.support

**Comment by BassXX** [comment]
i have added you to skype already, but there was no reply yet. Pls take a look at your skype :)

**Comment by BassXX** [comment]
Or maybe you could just upload the complete .php file, so I could make the search work

**Comment by lilmnm-kamikaze-** [comment]
HE did. that's whats in the pull request. what is the link to your version of the game? maybe he can look from there

**Comment by BassXX** [comment]
Okay here it is: http://ddclan.mrtv.biz/game
Thanks for helping me guys

**Comment by BassXX** [comment]
By the way: If I search for allies not from search page, but from the allies page, i receive the following SQL error:

Message: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

 Query-Code:SELECT id, ally_name, ally_tag, ally_members FROM uni1_alliance WHERE ally_universe = 1 AND ally_name LIKE %Admin Team% ORDER BY ( IF(ally_name = %Admin Team%t, 1, 0) + IF(ally_name LIKE %Admin Team%, 1, 0) ) DESC,ally_name ASC LIMIT 25;
File: /includes/classes/Database.class.php
Line: 109
URL: http://ddclan.mrtv.biz/game/game.php?page=alliance&mode=search
PHP-Version: 5.5.9-1ubuntu4.14
PHP-API: fpm-fcgi
MySQL-Cleint-Version: mysqlnd 5.0.11-dev - 20120503 - $Id: bf9ad53b11c9a57efdb1057292d73b928b8c5c77 $
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/classes/Database.class.php(176): Database->_query('SELECT id, ally...', Array, 'select')
 #1 /includes/pages/game/ShowAlliancePage.class.php(252): Database->select('SELECT id, ally...', Array)
 #2 /game.php(57): ShowAlliancePage->search()
 #3 {main}

**Comment by lilmnm-kamikaze-** [comment]
shouldnt this also look to see if the search text is like the Alliance tag instead of trying to search for the alliance name twice?

**Comment by BassXX** [comment]
I receive the same error if I search for the Alliance Tag

**Comment by lilmnm-kamikaze-** [comment]
that error shows its only looking for the name not the alliance tag

**Comment by BassXX** [comment]
Sorry, I don´t understand properly. What do you exactly recommend me to do?
