### ISSUE TITLE
Cannot delete personal notes

### ISSUE THREAD

**Issue by BassXX** [jkroepke/2Moons#155]
Hey people!

Unfortunately, I cannot delete the personal notes, which I wrote. Hope there is an easy way to solve this bug

**Comment by Hilarious001** [comment]
What does it do ? does the page simply refresh ? or do you get a message ?

**Comment by BassXX** [comment]
It just refreshes the page, but the personal note is still there

**Comment by Hilarious001** [comment]
really weird i compared my files to the default one no difference you are using default files or modified ones ?

**Comment by BassXX** [comment]
No modified files at all, I am using the github files (1.8.git version). The only file I have modified is the ShowSearchPage.php to make the player and planet search work

**Comment by jkroepke** [comment]
Works for me - Closed.
