### ISSUE TITLE
Installation issue. 

### ISSUE THREAD

**Issue by xpowert** [jkroepke/2Moons#157]
What the hell is this ? 

*******************************
Failed to create the database tables:

Undefined property: Database::$queryCount

*********************************
Cant even skip the instalation by installer and do it manualy.

**Comment by d3tr0l** [comment]
you need old source files and then put over it this new master files. works ok and if you do it properly you are not even going to have most of the issues reported here. and if you do, there will be like 2 of them and you can fix it yourself, it is php jeez.
at least be nice while reporting bugs and being just a leech.

**Comment by xpowert** [comment]
need to add one line in class DB . Next time when try to act smart try to
think out other solutions.

2016-03-19 21:54 GMT+02:00 d3tr0l <notifications@github.com>:

**Comment by xpowert** [comment]
I do not understand why should i download and uploud to my server older
version and then overwrite it by new files. Maybe you are right with that i
do not get most of bugs, but then this is so sick for newbies just like as
who havent used 2moons orginal files for a while

2016-03-20 3:15 GMT+02:00 Mārcis Veļikanovs <xpowertlatvia@gmail.com>:

**Comment by jkroepke** [comment]
You are downloading a old version of 2Moons im combo with a new PHP version.

See: https://github.com/jkroepke/2Moons/commit/c85605c6de2af341b224c8303d21cfb32ac3909e
