### ISSUE TITLE
Simulator not working

### ISSUE THREAD

**Issue by d3tr0l** [jkroepke/2Moons#158]
When clicking on calculate button, new window pops out, but it is blank instead of displaying the simulation. 
It was working in previous old versions.(1.7.3 working, after updating to current master it is not working)
Any help please? I really do not know where is the problem.

**Comment by Hilarious001** [comment]
if you get a blank page then you get a log in includes/error.log

Regards

**Comment by jkroepke** [comment]
Is this still valid?

**Comment by BassXX** [comment]
I think yes, because for me, I also get quite often a blank page when simulating. In the weekend I will check the error log and let you know

**Comment by jkroepke** [comment]
It is 100% reproduce? Basis on the given values, e.g...

**Comment by BassXX** [comment]
I will ask one of my users, he was able to reproduce i guess...Afterwards I will let you know

**Comment by bornhaeusser** [comment]
#0 /includes/pages/game/ShowBattleSimulatorPage.class.php(134): errorHandler(8, 'Undefined offse...', '/volume1/web/ga...', 134, Array)
#1 /game.php(57): ShowBattleSimulatorPage-&gt;send()
#2 {main}

**Comment by bornhaeusser** [comment]
if i reset the combat simulation first and start then entering the numbers -it works.....

**Comment by bornhaeusser** [comment]
got it - hope so - if i win the simulation blank page - if i lose it works.....

**Comment by bornhaeusser** [comment]
here is maybee the mistake inside (ShowBattleSimulatorPage.class.php):

if($combatResult['won'] == "a")
		{
			$stealResource = calculateSteal($attackers, array(
				'metal' => $BattleArray[0][1][1],
				'crystal' => $BattleArray[0][1][2],
				'deuterium' => $BattleArray[0][1][3]
			), true);

**Comment by Hilarious001** [comment]
can whe have the complete error log

**Comment by bornhaeusser** [comment]
[error.log.txt](https://github.com/jkroepke/2Moons/files/282252/error.log.txt)

**Comment by Hilarious001** [comment]
File: /volume1/web/game/2moons/includes/pages/game/ShowBattleSimulatorPage.class.php | Line: 134

can i have the from 130 to 137 of your file please

**Comment by bornhaeusser** [comment]
if($combatResult['won'] == "a")
		{
			$stealResource = calculateSteal($attackers, array(
				'metal' => $BattleArray[0][1][1],
				'crystal' => $BattleArray[0][1][2],
				'deuterium' => $BattleArray[0][1][3]
			), true);

**Comment by Hilarious001** [comment]
if($combatResult['won'] == "a")
		{
			$stealResource = calculateSteal($attackers, array(
				'metal' => $BattleArray[0][1][901],
				'crystal' => $BattleArray[0][1][902],
				'deuterium' => $BattleArray[0][1][903]
			), true);

here the fix

**Comment by bornhaeusser** [comment]
seems to work now, thx

**Comment by Hilarious001** [comment]
your welcome
