### ISSUE TITLE
How should we modify the database?

### ISSUE THREAD

**Issue by OzanKurt** [jkroepke/2Moons#163]
I am currently working on a new optional login system which will allow people to use an another database for its users to sign in.

@jkroepke How am I supposed to add the updates about the database to the code?

**Comment by OzanKurt** [comment]
A sneakpeak to the new feature:

### Admin Panel
![Images](http://img.prntscr.com/img?url=http://i.imgur.com/azeaBou.png)

### Todo
![Todo](http://img.prntscr.com/img?url=http://i.imgur.com/2WrA7JW.png)

**Comment by jkroepke** [comment]
Why do not use externalAuth Providors?

https://github.com/jkroepke/2Moons/tree/master/includes/classes/extauth

**Comment by OzanKurt** [comment]
Because I couldn't figure out how to. :/

And it will not allow people to register, its just for logging in from an another database.

**Comment by OzanKurt** [comment]
@jkroepke Awesome, I fixed the tiny facebook login error and now will learn how to implement a new one. I will also add some comment about what those functions does in the interface.

**Comment by jkroepke** [comment]
Also you can execute the register, if the use does not exists on the database.

You can also add function like a 2nd database connection to your auth database to verify the password.

**Comment by OzanKurt** [comment]
It will probably be something like logins from forums.
