### ISSUE TITLE
Multi universe support .htaccess

### ISSUE THREAD

**Issue by OzanKurt** [jkroepke/2Moons#164]
```
<IfModule mod_rewrite.c>
	RewriteEngine on
	RewriteRule uni([0-9]+)/?(.*)?$ $2 [L,QSA,E=UNI:$1]
</IfModule>
```

How does this append the universe so to the request?

**Comment by jkroepke** [comment]
Via environment variables.

mod_rewrite will prefix all environment variables with REDIRECT_, like REDIRECT_UNI

https://github.com/jkroepke/2Moons/blob/master/includes/classes/Universe.class.php#L84

**Comment by jkroepke** [comment]
Instead domain.com/uni1/ you can use uni1.domain.com.

But this require a domain wildcard vhost.

**Comment by jkroepke** [comment]
Its fine?

**Comment by OzanKurt** [comment]
Yeah yeah :D Great, subdomains will help me a lot.
