### ISSUE TITLE
Weird register issue

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#165]
Hello jan, i have a really really weird issue
I unchecked in admin panel the system of verifiyng emails when you register and i even completly deleted the code from the register page, so that people doesnt need to verify their email to be able to activate their account. weird thing is that i still have some time new registered players landing user activity list that need to activate their account via email, but all this code has been deleted from the files so how can this happen some times here and there ?

Regards

**Comment by jkroepke** [comment]
Do you have somethink like "Login with Facebook" ?
Maybe you should search for %%USERS_VALID%% in your code.

Otherwise, try to drop or rename the table. If somethink try to insert some date to the verify table, the game will be crash and log the error.

**Comment by Hilarious001** [comment]
Do you have somethink like "Login with Facebook" ?
=> no only real website registrations

 Maybe you should search for %%USERS_VALID%% in your code.
=> 1 result for the insert in database before redirecting to the vertify page

I will try to add a log to know why it dont redirect to veritfy page
