### ISSUE TITLE
CleanerCron Cronjob not working

### ISSUE THREAD

**Issue by BassXX** [jkroepke/2Moons#166]
Hey Guys,

I think the Cronjob, which should delete inactive players is not working for me. I have users, which are not active since more than 30 days, but they have not been deleted yet.

Any recommendations, what I could do?

**Comment by jkroepke** [comment]
Any error in error.log?

**Comment by BassXX** [comment]
Sorry to ask, but where I can find/view this file?

**Comment by jkroepke** [comment]
In the includes directory

**Comment by BassXX** [comment]
all right, thanks. I will take a look on weekend. Afterwards I will come back to you.

**Comment by BassXX** [comment]
Hey Guys,

I have Checked, I have no error.log file at all

**Comment by jkroepke** [comment]
Can you verify it, that the cronjob is not "locked"?

You will see the status on the admin control panel

**Comment by BassXX** [comment]
Yes. It is unlocked. BTW: I found the error.log file.( Sorry for that.)  But I could not find any error related to this cronjob. 

So this cronjob is not listed in the error log....but still not working. Is there another way to verify, wether the cronjob is working or not?

**Comment by jkroepke** [comment]
So you CleanerCronjob is not working... ?

**Comment by BassXX** [comment]
The Cronjob, which deletes users, that have not logged in within 30 days. Is it the CleanerCronjob?

Statistics, Records and Referals is working for me. Do you have any suggestions what I could do?

**Comment by jkroepke** [comment]
No. But I have the same Issue on my test instance. I will look into it..

BassXX <notifications@github.com> schrieb am Mo., 25. Apr. 2016, 02:31:

**Comment by Hilarious001** [comment]
Hello InactiveMail cronjob simply send a mail to players that are inactive depending on the value you have set in the admin panel
Nothing to do with deleting members after 30 days

Regards

**Comment by jkroepke** [comment]
CleanerCronjob should delete old users.

**Comment by BassXX** [comment]
I See.

Then i should have named the issue to CleanerCronjob not working. Sorry guys!

But thank you for helping me out with this! Hopefully we will find a solution soon!

**Comment by Hilarious001** [comment]
Then to ask the question again ? is it locked or not the cleanercronjob ?
Can you use on your includes/error.log file CTRL+F and search for cleanercronjob word in notepad++

Regards

**Comment by jkroepke** [comment]
Easy fix ...
