### ISSUE TITLE
Session error

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#168]
Hello nothing really changed since days exept for my vps hosting compagny and i suddently experience huge error logs file with the same error, sessionID might change, if i install using vestacp i have no problems once installed on a cpanelwhm server i get this error alot alot alot what can i do

[06-Mar-2016 03:49:28 Europe/Brussels] PHP Fatal error: Uncaught exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'userID' cannot be null

Query-Code:REPLACE INTO uni1_session SET
sessionID = 1ab21af39d2ebcb7e81fedcf18028e58,
userID = ,
lastonline = 1457232568,
userIP = 80.200.59.250;' in /home/xterium/public_html/includes/classes/Database.class.php:109
Stack trace:
#0 /home/xterium/public_html/includes/classes/Database.class.php(152): Database->_query('REPLACE INTO %%...', Array, 'replace')
#1 /home/xterium/public_html/includes/classes/Session.class.php(229): Database->replace('REPLACE INTO %%...', Array)
#2 [internal function]: Session->save()
#3 {main}
thrown in /home/xterium/public_html/includes/classes/Database.class.php on line 109

**Comment by OzanKurt** [comment]
Please change table engine to MYISAM

**Comment by jkroepke** [comment]
Why he should do this?

**Comment by jkroepke** [comment]
Do you have some customized login code?

**Comment by OzanKurt** [comment]
Its about INNODB binding the `userID` field with the id in users table, that's the reason you cant assign null to userID. In MYISAM there is no such thing.

**Comment by jkroepke** [comment]
Thats right. But its an error in 2moons somewhere that tryinig to save an session without an userId

**Comment by OzanKurt** [comment]
The we should log the actions.

**Comment by Hilarious001** [comment]
Hello i have a custom login page @ xterium.space
There should be no real problems with the file since with any other server panel than cpanel and whm i dont have this, i am using 10.0.24-MariaDB

Regards

**Comment by jkroepke** [comment]
Maybe you can add a ``$session->delete();`` before https://github.com/jkroepke/2Moons/blob/master/includes/common.php#L122 ?

**Comment by Hilarious001** [comment]
Hello jan i was able to reproduce the error, i have some ajax files that is working when you are logged in but that trigger that error when you are not logged in, so i maybe things its some one or a bot visiting those page and refreshing non stop as i was able to add my own session id and error in the logs,

Anyway, is there a way to check if a user is really logged in ?

That is my default ajax code at the begin of the file

define('MODE', 'BANNER');
define('ROOT_PATH', str_replace('\\', '/',dirname(__FILE__)).'/');
set_include_path(ROOT_PATH);
require 'includes/common.php';

$session	= Session::load();
$sql	= "SELECT * FROM %%USERS%% WHERE id = :userId;";
$USER	= Database::get()->selectSingle($sql, array(
':userId'	=> $session->userId
));

if(empty($USER))
	exit();

**Comment by jkroepke** [comment]
Somethink like 

```
	$session	= Session::load();

	if(!$session->isValidSession())
	{
	    $session->delete();
		HTTP::redirectTo('index.php?code=3');
	}
```

**Comment by jkroepke** [comment]
The concept of the session code is bad.

**Comment by Hilarious001** [comment]
Really weird my game doesnt generate that error on VESTACP as i just tried it again but i really want to use cpanel/whm

with your solution the error changed in a error with no session id and no userID

[24-Apr-2016 17:42:34 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'userID' cannot be null<br>
<br>
Query-Code:REPLACE INTO uni1_session SET
		sessionID	= ,
		userID		= ,
		lastonline	= 1461512554,
		userIP		= 181.167.35.12;' in /home/xterium/public_html/includes/classes/Database.class.php:109
Stack trace:
#0 /home/xterium/public_html/includes/classes/Database.class.php(152): Database->_query('REPLACE INTO %%...', Array, 'replace')
#1 /home/xterium/public_html/includes/classes/Session.class.php(230): Database->replace('REPLACE INTO %%...', Array)
#2 [internal function]: Session->save()
#3 {main}
  thrown in /home/xterium/public_html/includes/classes/Database.class.php on line 109

**Comment by jkroepke** [comment]
But i looks better for me.

With this, I can fix it in 2moons.

**Comment by jkroepke** [comment]
https://github.com/jkroepke/2Moons/commit/071234b574ff7f51d255bac8728c92bb0114eead

**Comment by Hilarious001** [comment]
Hello jan, i just want to thanks you :)
This indeed fixed my problems under cpanel/whm i have no problem anymore ?
You maybe know why under VESTACP i dont have this ? Do they maybe report less errors ?
Anyway thanks alot, if you want to send me your paypal email i will make a donation you really did great job all those years

**Comment by jkroepke** [comment]
Hi,

your are welcome. 

Anyway, i don't have any idea. Did you have any errors with CPanel? (Maybe Force override the error log level/path). Maybe CPanel has less strict MySQL options.

Anyway, you don't need to make a money donation. If you push your fixes to GitHub, it would the enough.
