### ISSUE TITLE
Error after last update

### ISSUE THREAD

**Issue by naiffuR** [jkroepke/2Moons#171]
Message: Undefined offset: 902
File: /cache/templates/ru^dc7aed9edd010fa550dfecdbd1d74140cc2ce4ba.page.buildings.default.tpl.php
Line: 765
URL: http://localhost/2moons/game.php?page=buildings
PHP-Version: 5.6.3
PHP-API: apache2handler
MySQL-Cleint-Version: mysqlnd 5.0.11-dev - 20120503 - $Id: f373ea5dd5538761406a8022a4b8a374418b240e $
2Moons Version: 1.8.git
Debug Backtrace:
#0 /cache/templates/ru^dc7aed9edd010fa550dfecdbd1d74140cc2ce4ba.page.buildings.default.tpl.php(765): errorHandler(8, 'Undefined offse...', 'H://xamppVC11//ht...', 765, Array)
#1 /includes/libs/Smarty/sysplugins/smarty_template_resource_base.php(122): content_572232ce5c2001_17205043(Object(Smarty_Internal_Template))
#2 /includes/libs/Smarty/sysplugins/smarty_internal_runtime_updatecache.php(108): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 /includes/libs/Smarty/sysplugins/smarty_template_cached.php(132): Smarty_Internal_Runtime_UpdateCache->updateCache(Object(Smarty_Template_Cached), Object(Smarty_Internal_Template), false)
#4 /includes/libs/Smarty/sysplugins/smarty_internal_template.php(152): Smarty_Template_Cached->render(Object(Smarty_Internal_Template), false)
#5 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(191): Smarty_Internal_Template->render(false, 1)
#6 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(109): Smarty_Internal_TemplateBase->_execute('extends:layout....', NULL, NULL, NULL, 1)
#7 /includes/classes/class.template.php(149): Smarty_Internal_TemplateBase->display('extends:layout....')
#8 /includes/pages/game/AbstractGamePage.class.php(249): template->display('extends:layout....')
#9 /includes/pages/game/ShowBuildingsPage.class.php(352): AbstractGamePage->display('page.buildings....')
#10 /game.php(57): ShowBuildingsPage->show()
#11 {main} 

When you enter the settings : Parse error: syntax error, unexpected '<' in H:\xamppVC11\htdocs\2Moons\cache\ru^b7de8e1ccadbd93187fa5d8ba92d0cdfc92549ab_1.extends.page.settings.default.tpl.cache.php on line 558

**Comment by jkroepke** [comment]
Which version are you using? How to reprocue this bug?

**Comment by BassXX** [comment]
I have the same problem over here! If you are clicking on buildings page,  the error will come. I am not able to access the buildings age at all. Please help! Without the buildings page ,the gameplay cannot continue


NOTICE

Message: Undefined offset: 902
File: /cache/templates/de^648c15144420c995aa38db671a7c9efe84a90792.page.buildings.default.tpl.php
Line: 765
URL: http://ddclan.mrtv.biz/game/game.php?page=buildings
PHP-Version: 5.5.9-1ubuntu4.14
PHP-API: fpm-fcgi
MySQL-Cleint-Version: mysqlnd 5.0.11-dev - 20120503 - $Id: bf9ad53b11c9a57efdb1057292d73b928b8c5c77 $
2Moons Version: 1.8.git
Debug Backtrace:
#0 /cache/templates/de^648c15144420c995aa38db671a7c9efe84a90792.page.buildings.default.tpl.php(765): errorHandler(8, 'Undefined offse...', 'FILEPATH ...', 765, Array)
 #1 /includes/libs/Smarty/sysplugins/smarty_template_resource_base.php(122): content_572469d6e057c6_55875809(Object(Smarty_Internal_Template))
 #2 /includes/libs/Smarty/sysplugins/smarty_template_cached.php(126): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
 #3 /includes/libs/Smarty/sysplugins/smarty_internal_template.php(152): Smarty_Template_Cached->render(Object(Smarty_Internal_Template), false)
 #4 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(191): Smarty_Internal_Template->render(false, 1)
 #5 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(109): Smarty_Internal_TemplateBase->_execute('extends:layout....', NULL, NULL, NULL, 1)
 #6 /includes/classes/class.template.php(149): Smarty_Internal_TemplateBase->display('extends:layout....')
 #7 /includes/pages/game/AbstractGamePage.class.php(249): template->display('extends:layout....')
 #8 /includes/pages/game/ShowBuildingsPage.class.php(352): AbstractGamePage->display('page.buildings....')
 #9 /game.php(57): ShowBuildingsPage->show()
 #10 {main}

**Comment by BassXX** [comment]
I am using the newest version
