### ISSUE TITLE
Acs improvements

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#174]
Hello @jkroepke i recently improved your acs system to work like the real ogame if you used antigame and i was wondering if you could see this as a good module to implent in the core 2moons or not as you said, all depend on the feature ?

http://hpics.li/2610323
http://hpics.li/7f6931f
http://hpics.li/9fc0582
http://hpics.li/c15ee3c

**Comment by OzanKurt** [comment]
What is ACS?

**Comment by jkroepke** [comment]
http://owiki.de/index.php/Allianzkampfsystem

Ozan Kurt <notifications@github.com> schrieb am Mo., 2. Mai 2016, 01:33:

**Comment by jkroepke** [comment]
Whats the difference between 2Moons and OGame?

**Comment by Hilarious001** [comment]
did you ever used ACS system
First of all on ogame you have a max possibilitie of 30% of total time left to add your fleets
right now on 2moons you can even add them 2 days later
The picture show in green zhen you dont delay the acs Time left before to late / 00:00:00
In orange when you delay the acs time left before to late / dalay of main acs
Red if you are to late to add your fleets 00:00:00/ time to late

You can get the info on fleetstep 1 and 2 

Regards

**Comment by jkroepke** [comment]
> on 2moons you can even add them 2 days later

Okay, this is a bug. I was think, it was already implemented..

**Comment by Hilarious001** [comment]
No its not implented
also what is not very users friendly is that once you have invited a player at this moment the invited player doesnt know when the first fleets will hit the target without asking to the player that invited
with this hook you can see what is the maximum time left you can send, time left before maximum time has been reached, time that you delayed the ships and time when you are to late. Another thing that i had to change was your flotten;js file as when you select on fleetstep1 an acs shortcut, and after that you select your speed %, then with the updatevars function the acs fleetgroup is auto removed, so you have to select acs target, change speed and select again acs target

If you want i can publish the code and you might want to improve it.
The info on fleetstep1 show when you click on the acs shortcut and goes again away if you change coords and planetype but not when u change speed
On fleetstep2 it appaers only when you click acs mission and goes away if you select another mission after all

 its under testign phase by my players and it seems to work very good and they really like it (the raiders part of my game, those that really use it)

Regards
