### ISSUE TITLE
.extends.page.settings.default.tpl.cache.php on line 558

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#177]
Did get an error after entering the SettingPage.

Parse error: syntax error, unexpected '<' in /2moons/cache/en^9bbd8850b86195c5c9a40362e544aa71c22b06b8_1.extends.page.settings.default.tpl.cache.php on line 558

**Comment by Hilarious001** [comment]
you probably did a mistake in your file
open that cache file check line 558 and report it to us
but you probably have a < at the begin of your php or tpl file

**Comment by bornhaeusser** [comment]
This is my line 558

<?php if ($_smarty_tpl->tpl_vars['ref_active']->value) {?>index.php?ref=<?php echo $_smarty_tpl->tpl_vars['userid']->value;?>

**Comment by bornhaeusser** [comment]
Line 560 looks for me strange, after <?php the "}"

<?php }?>"><img src="<?php echo @constant('PROTOCOL');

**Comment by Hilarious001** [comment]
sorry my fault i guess you recently downloaded the 2moons pack?
I have the same error since i updated with the new smarty change on my referal page
didnt really sorted it out, i will look tonight and will keep u updated
@jkroepke 
Regards

**Comment by bornhaeusser** [comment]
I Downloaded the master from git. 
That Package I used.

**Comment by Hilarious001** [comment]
yes i know but its a recent download ? less then 16 days ago ?
I think i found the error didnt tested it yet as i am alot on my rl work i will try it tonight and ill keep u updated

**Comment by bornhaeusser** [comment]
sounds good.

**Comment by BassXX** [comment]
Same issue over here.

**Comment by jkroepke** [comment]
Looks like an smarty bug..
