### ISSUE TITLE
The MySQL server has gone away (error 2006)

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#178]
THIS IS MORE FOR INFORMATION AS THE PACK ITSELF IT WORKING FINE!!

Hello @jkroepke, i have a small question i would like to try to find a correct answer
i am at the day that we reached the 3.000 registered account in less then 3 month (Thing i am really glad on) but i am occuring new problems then when i only had 100 registered account with my database.

I have some problems with the code not be able to manage all queries on time and i am getting the error 2008 lost connexion with database, do you have any way to maybe fix that or a way i can maybe addapt the code ? because cronjobs are some time being locked due to that as it cant finish the queries (Example stats update or delete inactives.) and players are receiving ingame errors with my sql password and user shown (not a real problem since my database is well secured) i have searched on the internet and most say to increase the max_allowed_packet value but even if i put it higher it sometimes occur and i dont really know how high i can go with that value. maybe you have any idea to optimize all this ?

And what i find weird is the mail i am receiving when those cronjobs are running that looks very high

User: ******
Domain: ******.*****
MySQL Connection Limit:
Current MySQL Connections: 51

As information:
DEDICATED SERVER
Intel  Xeon E3
E5-1620v2	4c/8t  
3,4 / 3,8 GHz	32 Go RAM
DDR3 ECC 1600 MHz	2x2To  SOFT

[mysqld]
default-storage-engine=MyISAM
innodb_file_per_table=1
max_allowed_packet=268435456
open_files_limit=10000
#bind-address=127.0.0.1
tmpdir=/home/mysqltmp
local-infile=0
slow_query_log
log-error
max_connections = 600
max_user_connections=1000
[mysqld_safe]
[mysqldump]
quick
max_allowed_packet = 16M
[isamchk]
key_buffer = 384M
sort_buffer = 384M
read_buffer = 256M
write_buffer = 256M
[myisamchk]
key_buffer = 384M
sort_buffer = 384M
read_buffer = 256M
write_buffer = 256M
#### Per connection configuration ####
sort_buffer_size = 5M
join_buffer_size = 5M
thread_stack = 192K

**Comment by jkroepke** [comment]
Its related to a query?

**Comment by Hilarious001** [comment]
I guess so its not able to finish the query on time and it lose connexion with the database.
Another example is when sending global message from admin panel with default file, its not able to send to all users on time so alot of users are not getting the global message send by admin
When i send via language, i get the message in all language for each lang avaible even if i select a specific language when i am playing in english.
And in my error.log file i have the error but i will have to wait this evening to give more details as now i dont remember if its error lost connexion with database or if it was error The MySQL server has gone away (error 2006)

**Comment by jkroepke** [comment]
Did you look at the error log from mysql server?

**Comment by Hilarious001** [comment]
i am at rl work and didnt had alot of time to concentrate on it
i will be able to shoot more info this weekend about this

Regards

**Comment by jkroepke** [comment]
Anyway, the statistical cronjob generate. I added some limits to avoid there:

https://github.com/jkroepke/2Moons/commit/ffb4350f466505f4a14f1f6d9bd05778840bb120

**Comment by Hilarious001** [comment]
You can close this i fixed my problem with another solution, in mysql error log there is nothing special exept lost connexion with database either

i guess its my cronjob being to big and taking to much times, since i know the cronjob runs for a period of 1 minutes each time you click on a button ingame with 150 users online it runs alot of time, i decided to divide my big cronjob in 10 different steps, each click while the cronjob runs will apply one step, (so the 10 first players clicking on a menu) once all steps are over it does not run it anymore, even if the minutes is not over. atleast my cronjob is working back again this time without 2min page load and a locked cronjob at the end, it goes smoothly, so in case of if you have a huge database, you will have to divide the cleaner cronjob

**Comment by jkroepke** [comment]
You should be use cronjobs started by the system (with crontab).
