### ISSUE TITLE
Not all Officers

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#184]
Hi in the Game i only see 2 Officers - but in the Giveaways much more...
<img width="829" alt="bildschirmfoto 2016-05-21 um 23 34 58" src="https://cloud.githubusercontent.com/assets/6609040/15450945/e03c3b62-1fac-11e6-816e-ed925ec2429c.png">

<img width="964" alt="bildschirmfoto 2016-05-21 um 23 35 16" src="https://cloud.githubusercontent.com/assets/6609040/15450946/e403ae24-1fac-11e6-91ff-3eed7b836d5f.png">

**Comment by jkroepke** [comment]
Checkout the Techtree. Officers has some dependencies.

**Comment by bornhaeusser** [comment]
uuh..... sh.... sorry. 
(Schäme mich in Grund und Boden.....)
