### ISSUE TITLE
blank page combat simulation

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#191]
Hi i get a blank page if i do a CombatSimulation

<img width="1021" alt="bildschirmfoto 2016-05-24 um 17 40 00" src="https://cloud.githubusercontent.com/assets/6609040/15510157/9a722246-21d6-11e6-87ad-3a155b24a4ae.png">

**Comment by jkroepke** [comment]
We need more informations. Any entries in error.log? It is 100% to reproduce? 

See #158, I will close this.

**Comment by bornhaeusser** [comment]
[25-May-2016 11:01:16] NOTICE: "Undefined offset: 1"
File: /2moons/includes/pages/game/ShowBattleSimulatorPage.class.php | Line: 134
URL: /game.php?page=battleSimulator&mode=send | Version: 1.8.git
Stack trace:
#0 /includes/pages/game/ShowBattleSimulatorPage.class.php(134): errorHandler(8, 'Undefined offse...', '/volume1/web/ga...', 134, Array)
#1 /game.php(57): ShowBattleSimulatorPage-&gt;send()
#2 {main}
