### ISSUE TITLE
Url of the logo

### ISSUE THREAD

**Issue by Eldarya** [jkroepke/2Moons#193]
Hi I want to make sure that clicking on the logo you go directly to the home instead of on the changelog page, but can not find the string to edit. Can you tell me what is?

**Comment by Hilarious001** [comment]
the only string i know about changelog is 
https://github.com/jkroepke/2Moons/blob/master/styles/templates/game/main.navigation.tpl#L3

**Comment by Eldarya** [comment]
That's right, I found the string! Thank you!
