### ISSUE TITLE
new Cronjob

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#194]
I am not able to create a new cronjob in the admin menu after the latest update.
(Klivking on create new cronjob it just refresh the list)

Error log no entries.

**Comment by Hilarious001** [comment]
I dont post a fix as i didnt tried it yet,
but i take the time to report you my old error jan, that other people have to
https://github.com/jkroepke/2Moons/commit/ffb4350f466505f4a14f1f6d9bd05778840bb120

Regards
