### ISSUE TITLE
Alliance - Cancel Request

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#197]
If we cancel a Alliance Request it comes to an Error:

[28-May-2016 10:02:46] USER ERROR: "Incorrect Update Query"
File: /volume1/web/game/2moons/includes/classes/Database.class.php | Line: 158
URL: https://db-cloud.de/game/2moons/game.php?page=alliance&mode=admin&action=diplomacyDelete&id=1 | Version: 1.8.git
Stack trace:
#0 /includes/pages/game/ShowAlliancePage.class.php(1559): Database-&gt;update('DELETE FROM %%D...', Array)
#1 /includes/pages/game/ShowAlliancePage.class.php(746): ShowAlliancePage-&gt;adminDiplomacyDelete()
#2 /game.php(57): ShowAlliancePage-&gt;admin()
#3 {main}

[28-May-2016 10:03:52] USER ERROR: "Incorrect Update Query"
File: /volume1/web/game/2moons/includes/classes/Database.class.php | Line: 158
URL: https://db-cloud.de/game/2moons/game.php?page=alliance&mode=admin&action=diplomacyDelete&id=1 | Version: 1.8.git
Stack trace:
#0 /includes/pages/game/ShowAlliancePage.class.php(1559): Database-&gt;update('DELETE FROM %%D...', Array)
#1 /includes/pages/game/ShowAlliancePage.class.php(746): ShowAlliancePage-&gt;adminDiplomacyDelete()
#2 /game.php(57): ShowAlliancePage-&gt;admin()
#3 {main}

**Comment by jkroepke** [comment]
Fixed in #201
