### ISSUE TITLE
Translation not apply

### ISSUE THREAD

**Issue by Eldarya** [jkroepke/2Moons#199]
Hi, I translated some 'in-game' parties but despite having deleted the cache does not appear, as I solve?

EX:

https://i.gyazo.com/6fdcf06726b770b5fcdd3917e3475c7b.png
https://i.gyazo.com/68638d0a79c3b85e393a83e154b1aeb6.png

**Comment by jkroepke** [comment]
Checkout the LANG.cfg on your language. 2Moons detect languages by the values in the LANG.cfg

**Comment by Eldarya** [comment]
I set this: https://gyazo.com/f9470300981d8284655081621ac3cfb2

The login was translated smoothly, alone problems with the part in-game

**Comment by jkroepke** [comment]
Did your set your language to it on the player settings page?
