### ISSUE TITLE
Sort of Hall Of Fame

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#203]
If i sort the Hall of Fame to date the rank does not change...
All sortings Show rank 1 on position 1

<img width="600" alt="bildschirmfoto 2016-05-30 um 21 55 07" src="https://cloud.githubusercontent.com/assets/6609040/15657465/546bd262-26b1-11e6-9a60-15a997027369.png">
<img width="587" alt="bildschirmfoto 2016-05-30 um 21 55 19" src="https://cloud.githubusercontent.com/assets/6609040/15657466/55dc04be-26b1-11e6-81db-6eb678ce6d5a.png">

**Comment by Hilarious001** [comment]
its not an error it simply show you the rank from 1 to 100 in function of your order type as there is no real way to get the position of each hit since its not stored into the database
so ordering by date show you each time the hits from 1 => 100

**Comment by bornhaeusser** [comment]
Ok thanks
