### ISSUE TITLE
Create a in-game page.

### ISSUE THREAD

**Issue by Eldarya** [jkroepke/2Moons#204]
Hi, How do I create a page in-game? I tried via includes / page but says it does not exist ..

**Comment by jkroepke** [comment]
Create a file calling includes/pages/ShowNamePage.php with content:

```
<?php

class ShowNamePage extends AbstractGamePage
{
	public static $requireModule = 0;

	function __construct() 
	{
		parent::__construct();
	}
	
	function show() 
	{
		echo "Welcome!";
	}
}
```

Then you can open `game.php?page=name`

**Comment by Eldarya** [comment]
I have tried, and the result is not changed

Screen
https://i.gyazo.com/3295a83b59e783153a1b01fa537de2a0.png
https://i.gyazo.com/9726416cf0337780a2637966c2253697.png

**Comment by jkroepke** [comment]
Sorry, includes/pages/ShowNamePage.class.php should be right.

**Comment by Eldarya** [comment]
I built everything as indicated, but I get this error:
https://i.gyazo.com/75041923356e99e644eea3912d02dba0.png

**Comment by jkroepke** [comment]
Can you paste the file?

**Comment by Eldarya** [comment]
I wrote in this file:

`<?php

class ShowNamePage extends AbstractGamePage
{
    public static $requireModule = 0;

    function __construct() 
    {
        parent::__construct();
    }

    function show() 
    {
        echo "Welcome!";
    }
}`

**Comment by jkroepke** [comment]
It looks like you have called `game.php?page=unr `

**Comment by Eldarya** [comment]
That's right, but if I visit the page gives me the error of screenshot
https://i.gyazo.com/75041923356e99e644eea3912d02dba0.png

**Comment by jkroepke** [comment]
If so, you have to name the class `ShowUnrPage `

**admin.php?page=unr**

`includes 'includes/pages/game/ShowUnrPage.class.php'`

and calling the class `ShowUnrPage`

`admin.php?page=<page>` -> `Show<Page>Page.class.php` -> `class Show<Page>Page`

**Comment by Eldarya** [comment]
Now the page works, but it is not integrated to the site!
Screen: https://i.gyazo.com/eab8556c9d503fe80077eb4e2ed833ee.png

**Comment by jkroepke** [comment]
Use the Changelog Page as example. Also you have to create a template.

Eldarya <notifications@github.com<mailto:notifications@github.com>> schrieb am Mi., 1. Juni 2016, 12:14:

Now the page works, but it is not integrated to the site!
Screen: https://i.gyazo.com/eab8556c9d503fe80077eb4e2ed833ee.png
