### ISSUE TITLE
Kick users from alliance

### ISSUE THREAD

**Issue by intro94** [jkroepke/2Moons#205]
Hello, Jan!
In the method `adminMembersKick()` (in the ShowAlliancePage class), there is no verification of the user alliance. Anyone who has the kick-rights can use url with the user ID from another alliance and kick him out. Has recently several Russian projects were subjected to mass kick from alliances.
On the old version 2moons I have fix:
```
...
$verUserAlly = $GLOBALS['DATABASE']->uniquequery("SELECT `ally_id` FROM ".USERS." WHERE `id` = ".$id.";");
if($verUserAlly['ally_id'] != $USER['ally_id'])
	$this->redirectToHome();
...
```
Best regards, Yuri.
P.S.: Sorry for my bad English. I do not speak English. I use a translator and edit the translation. :(

**Comment by jkroepke** [comment]
I added a check, hopefully it will be works as expected.
