### ISSUE TITLE
Update stat create some problem with PHP7.0.7-4 and number of users >49

### ISSUE THREAD

**Issue by BigTwoProduction** [jkroepke/2Moons#211]
Hey everybody,

I've update my server to PHP 7.0.7 & MySQL server to 5.7.12-1 ( all of my configuration can be found here [http://big-two.tk/info.php](url) )

So with PHP 7 series MySQL is no more available we must must MySQLi isn'it ?

Let me explain a littel bit, i've not my server during one month to change my carrier. So I've take last git available on gitHub for 2Moons. I've put back last database from one month ago. every think work ok execpt generation of stat. Error is follow: 

> [07-Jun-2016 03:06:59] USER ERROR: "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1"
File: /var/www/html/xnovareborn/includes/classes/Database.class.php | Line: 242
URL: http://www.big-two.tk/xnovareborn/cronjob.php?cronjobID=2 | Version: 1.8.git
Stack trace:
#0 /includes/classes/Database.class.php(242): PDO-&gt;query('INSERT INTO  un...')
#1 /includes/classes/class.statbuilder.php(158): Database-&gt;nativeQuery('INSERT INTO  un...')
#2 /includes/classes/class.statbuilder.php(400): statbuilder-&gt;SaveDataIntoDB('INSERT INTO  %%...')
#3 /includes/classes/cronjob/StatisticCronjob.class.php(27): statbuilder-&gt;MakeStats()
#4 /includes/classes/Cronjob.class.php(57): StatisticCronjob-&gt;run()
#5 /cronjob.php(54): Cronjob::execute(2)
#6 {main}

Or the strange fact is when number of users is under 49 that work well ( except the writes date of last updated stat in game) 

Here information of update (with 45 users in database) when it work :

>Statistiques mises à jour! 
Détails :
Stats mises à jour : secondes<
Mémoire utilisée au début : 1875.7 KB / max. 2048 KB
Mémoire utilisée à la fin : 2534.9 KB / max. 2048 KB
Crête Mémoire: 2695.3 KB / max. 2048 KB 
Requêtes SQL : 37

Before no problem with PHP5. 

If somebody can help me :)

P.S: I've near reach full translation in french language !!! 

Best regards,
Jordan.

**Comment by Hilarious001** [comment]
Hello this is because jan made a commit in the statupdater file some weeks ago
i told him this error but he told me he didnt had this
You can revert the commit or wait for someone that have some time to fix it
https://github.com/jkroepke/2Moons/commit/ffb4350f466505f4a14f1f6d9bd05778840bb120

**Comment by BigTwoProduction** [comment]
Ha thanks you've right ! Now without last commit on "class.statbuilder.php" it's ok !

Thanks @Hilarious001 :) :+1:

**Comment by jkroepke** [comment]
> i told him this error but he told me he didnt had this

Sometime I forgot things. Next time, I create a new issue like this.
