### ISSUE TITLE
Phalanx visibility

### ISSUE THREAD

**Issue by ogamemaster** [jkroepke/2Moons#213]
Hy
I like to ask where i find the files when is allowed and ignored Phalanx visibility
when sent the fleet from Planet and when from moon 
thanks

**Comment by jkroepke** [comment]
Did you mean this?

https://github.com/jkroepke/2Moons/blob/master/includes/pages/game/ShowPhalanxPage.class.php#L23

**Comment by ogamemaster** [comment]
thanks but no!
The player use phalanx to see the target planet fleet movements

**Comment by jkroepke** [comment]
Checkout https://github.com/jkroepke/2Moons/blob/master/includes/classes/class.FlyingFleetsTable.php

The phalanx using the same code as the fleet overview on the overview. The difference is the IsPhalanx m as you can see in some conditons.

**Comment by ogamemaster** [comment]
8 => 'harvest',where is this code for debris when fleet is invisible from moon and visible from planet
because only moon to moon and moon debris is invisible !

**Comment by jkroepke** [comment]
You can only phalanx on planets. and you are able to see just fleet from this planet or to this planet.

**Comment by ogamemaster** [comment]
Investigate position [1:45:6] (5)

Fleet in movement
00:14:30
One of your Fleets from Moon Moon [1:42:1] reached the debris [1:45:6]. Mission: Recycle
00:36:16
One of your Fleets returns from debris [1:45:6] back to planet Moon Moon [1:42:1]. Mission: Recycle

**Comment by jkroepke** [comment]
A fine. If we are in phalanx mode, we shoud ignore fleet to fleet_planet_type =! 1

Viele Grüße,
Jan-Otto Kröpke

2016-06-09 20:37 GMT+02:00 ogamemaster <notifications@github.com<mailto:notifications@github.com>>:

Investigate position 1:45:6<http://5>

Fleet in movement
00:14:30
One of your Fleets from Moon Moon [1:42:1] reached the debris [1:45:6]. Mission: Recycle
00:36:16
One of your Fleets returns from debris [1:45:6] back to planet Moon Moon [1:42:1]. Mission: Recycle

**Comment by ogamemaster** [comment]
where need to add this code and how?
thanks

**Comment by jkroepke** [comment]
I will create a fix.

**Comment by jkroepke** [comment]
Should be fixed right now.

**Comment by ogamemaster** [comment]
hide fleets moon <->debris on phalanx is ok 

but 

Investigate position [1:1:3] (500 h1)
Fleet in movement
00:43:02 	A hostile Fleets from player world [PM] from Moon Moon [1:19:11] reached the Planet 500 h1 [1:1:3]. Mission: Attack
01:16:07 	A hostile Fleets from player world [PM] from Planet Main Planet [1:19:11] reached the Planet 500 h1 [1:1:3]. Mission: Attack


Investigate position [1:19:11] (Main Planet)
Fleet in movement
01:17:46 	One of your Fleets from Planet Main Planet [1:19:11] reached the Planet 500 h1 [1:1:3]. Mission: Attack
03:13:16 	One of your Fleets returns from Planet 500 h1 [1:1:3] back to Planet Main Planet [1:19:11]. Mission: Attack

Moon attacks not show returning time only from planet

**Comment by jkroepke** [comment]
I do not understand you.

**Comment by ogamemaster** [comment]
2 attacks 
1 attacks from moon 
1 attacks from planets
to 1.1.3 from 1.19.11

Returnet fleet is only 1 attack from planet

**Comment by ogamemaster** [comment]
sorry :) thanks
great fix

**Comment by jkroepke** [comment]
Fine.
