### ISSUE TITLE
How i can pull request to add french translation string

### ISSUE THREAD

**Issue by BigTwoProduction** [jkroepke/2Moons#215]
Hey,

I can send french translation. It's a first version.
How i can pull request to add french translation string ?

Can i send to you a .rar files or how i the right way ?

Best regards,
Jordan.

**Comment by jkroepke** [comment]
Hi,

You can send me a **zip** file. But this is not the way how git and GitHub works.

I you want to be a cool guy, use git and pull request. But there is a little overhead. 

See: https://www.thinkful.com/learn/github-pull-request-tutorial/

**Comment by jkroepke** [comment]
Closed for inactivity.
