### ISSUE TITLE
Combat result colour

### ISSUE THREAD

**Issue by terassiel** [jkroepke/2Moons#216]
Both the ingame battle report messages (the inbox overview not the proper report) from MissionCaseDestruction and MissionCaseAttack are always in a white colour, no matter the combat result. Its correctly coloured in the battlehall and for expedition fights. I am using the latest file versions.
I am suspecting one of these functions but i am not sure:
$thisClass	= $class[$i];
$class			= array('raportWin', 'raportLose');

**Comment by jkroepke** [comment]
Correct. Fixed.
