### ISSUE TITLE
MissionDestruction not returning fleet

### ISSUE THREAD

**Issue by onova** [jkroepke/2Moons#218]
Hello, in my test server, for some reason, users are receiving negative time in destruction mission [which cause fleet not returning]. I tried to verify in MissionCaseDestruction.php if was something about when fleet returns from fight but did not found an issue yet.

Anyone has this issue?

Many thanks.

**Comment by jkroepke** [comment]
Normally this would be happens, with an error occurred. In the fleet list on the admin panel, you should see that the fleet is locked and an error must be logged in the error.log

**Comment by onova** [comment]
Yes fleet looks locked in Fleet panel.

I will check error.log and provide more information

**Comment by onova** [comment]
[17-May-2016 12:27:34 Europe/Berlin] PHP Parse error:  syntax error, unexpected end of file, expecting function (T_FUNCTION) in /public_html/includes/classes/missions/MissionCaseDestruction.class.php on line 651

The line 651, as the error says, it's end of file and I did not changed this file.

**Comment by jkroepke** [comment]
What did you are using? An normal https://github.com/jkroepke/2Moons/blob/master/includes/classes/missions/MissionCaseDestruction.class.php has only 637 lines.

**Comment by onova** [comment]
I was using old file before the unify copyright update. Using the current one, it persists.

I've noticed this happens in the following state:
- when achieves the enemy planet
- when you call fleet for return

**Comment by jkroepke** [comment]
Should be fixed right now

**Comment by onova** [comment]
Thanks
