### ISSUE TITLE
Mission Color

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#219]
The color of the text behind mission: should be an other, because you get information if you go over it with the mouse - i think.....

![ohne titel](https://cloud.githubusercontent.com/assets/6609040/15987078/f9ff06a4-301b-11e6-9132-9800f2edfa71.jpg)

**Comment by Hilarious001** [comment]
Hello, no problem with that, what you are asking is somethign to make it smoother, but not a bug,
you can freely change it here https://github.com/jkroepke/2Moons/blob/master/includes/classes/class.FlyingFleetsTable.php#L265
