### ISSUE TITLE
More enhancement than issue: Show number of online players for everyone

### ISSUE THREAD

**Issue by BassXX** [jkroepke/2Moons#220]
I would like to show in the overview, how much players are online at the moment. I know there is a menu in the ACP which shows the total number of online players.

I think it could be possible to display this variable in the overview main page for everyone. What is the name of this variable? What would I need to consider, any tips? :)

Thank you very much!

Greetings, BassXX

**Comment by onova** [comment]
```
$sql = "SELECT COUNT(*) as count FROM %%USERS%% WHERE universe = :universe AND onlinetime >= :time ;";
	$OnlineUsers = $db->selectSingle($sql, array(
			':universe'	=> Universe::current(),
			':time'	=> (TIMESTAMP - 3600 * 24),
	), 'count');
```

Then you assign on template.

**Comment by jkroepke** [comment]
I going not to implement this feature, because it will blame inactive games. Also if Player Online equals to one, you do everything save.
