### ISSUE TITLE
How to change speed factors of uni ?

### ISSUE THREAD

**Issue by ttpro1995** [jkroepke/2Moons#221]
![speed](http://i.imgur.com/Iumeo7l.png)
I want to change speed factors.
But these text is not editable.
What should I do ?

**Comment by bornhaeusser** [comment]
you can change it in the universum configuration.

**Comment by ttpro1995** [comment]
@bornhaeusser, thank you for reply 
 please help me navigate to universum configuration.
Some screenshot will be helpful.

**Comment by bornhaeusser** [comment]
in the administration panel in the right panel under the 2moons picture you find the Universe Configuration

**Comment by jkroepke** [comment]
Valid values:

1 = Normal speed
2 = 2x speed

and so on.

**Comment by ttpro1995** [comment]
Found it, thank @bornhaeusser .
By the ways, it is on LEFT panel.
![universer](http://image.prntscr.com/image/daaa9484452140b9beead8d16268a517.png)

**Comment by bornhaeusser** [comment]
uuh sorry.... left right problems :-)
