### ISSUE TITLE
What is "Multi Alarm?"

### ISSUE THREAD

**Issue by wardrich** [jkroepke/2Moons#222]
I keep getting "Multi Alarm" when I try to dispatch fleets.  What does this error mean?

**Comment by onova** [comment]
multi account interaction

**Comment by wardrich** [comment]
Sorry...  I'm not sure what that means still.

**Comment by BassXX** [comment]
that means, you have 2 different Accounts with the same IP Address. Multi Alarm is to prevent ppl from having multiple accounts.

However, I think you can disable the Multi Alarm in the ACP

**Comment by onova** [comment]
Yes you can, click on Multi IP Accounts button, then click on the red X to allow that account to allow missions against same ip account

**Comment by jkroepke** [comment]
> that means, you have 2 different Accounts with the same IP Address. Multi Alarm is to prevent ppl from having multiple accounts.

> However, I think you can disable the Multi Alarm in the ACP

Correct.
