### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#224]
Hello jan,

Did you wanted to add something else on this line or is the min() an error from your part ?
https://github.com/jkroepke/2Moons/blob/master/includes/classes/class.FleetFunctions.php#L155
this error WARNING: "min(): Array must contain at least one element"

Regards

**Comment by jkroepke** [comment]
Hi!

please use a qualified title for you issue.

**Comment by jkroepke** [comment]
GetFleetMaxSpeed is called with an empty array as argument.

Normally this does not happens. (I think)

Catch the case with 
```
if empty($fleet); return 0;
```
should be the best.

**Comment by jkroepke** [comment]
should be fixed right now

**Comment by Hilarious001** [comment]
Thanks, and yes sorry for the title
