### ISSUE TITLE
Chat Windows Settings

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#226]
Hi the settings in the Caht Windows look slike:

![image](https://cloud.githubusercontent.com/assets/6609040/16149585/14010f00-3492-11e6-98c0-a7f9097b6c6b.png)

**Comment by jkroepke** [comment]
Resolution?

**Comment by bornhaeusser** [comment]
several resolutions. (at the moment 2880x1800)

**Comment by jkroepke** [comment]
Should be fixed right now.

**Comment by BassXX** [comment]
For me it is still the same problem :/

**Comment by jkroepke** [comment]
Did you clear the cache? CSS is always cached by the browser.

Viele Grüße,
Jan-Otto Kröpke

2016-06-18 14:41 GMT+02:00 BassXX <notifications@github.com<mailto:notifications@github.com>>:

For me it is still the same problem :/

**Comment by BassXX** [comment]
I did, but still not working sorry

**Comment by jkroepke** [comment]
![bildschirmfoto 2016-06-18 um 19 31 59](https://cloud.githubusercontent.com/assets/1560587/16172509/65a35508-358b-11e6-853b-128c675a065c.png)

Its fine for me (Chrome).

**Comment by bornhaeusser** [comment]
also fine for me now.

**Comment by BassXX** [comment]
The settings is working for me too, but not the help window. try to click on the question mark

**Comment by bornhaeusser** [comment]
you are right. ? still wrong

**Comment by jkroepke** [comment]
Never try this help window, haha.
