### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#227]
If i changed the Theme in my settings and come back to the the settings page later i change something the theme everytime select theme1. (if i open the page the theme is always selectet theme1 even if i have an other theme)

**Comment by jkroepke** [comment]
Does it help, when you clear the cache?

**Comment by bornhaeusser** [comment]
no...

**Comment by Hilarious001** [comment]
are you sure values are updated in uni1_users did you verfied ?

**Comment by bornhaeusser** [comment]
Yes it changed in the db but if i reenter the setting page it shows entry one - if i then safe the settings without a change on the page it set the showing entry one.

**Comment by jkroepke** [comment]
Can you check, if the fix is working for you?
