### ISSUE TITLE
Teamspeak3 does not work

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#228]
Teamspeak does not work.

Did testet serveral settings but always:

Teamspeak	TeamspeakServer zurzeit nicht erreichbar. Wir bitten um Verständnis.

Querry does work over Telnet to the TS3 Server with Username and Password

**Comment by bornhaeusser** [comment]
[20-Jun-2016 15:46:25 Europe/Berlin] PHP Fatal error:  Cannot redeclare class ts3admin in 2moons/includes/libs/teamspeak/ts3admin/ts3admin.class.php on line 45

**Comment by BigTwoProduction** [comment]
Hey, 

Ts3 module works well. For this error you must replace "require" by "require_once" that all ;).  To keep ts3 module at the latest update you must take photos file of this package "http://ts3admin.info". 

Best regards,
Jordan.

**Comment by bornhaeusser** [comment]
where i have to set require_once

**Comment by jkroepke** [comment]
https://github.com/jkroepke/2Moons/blob/master/includes/classes/cache/builder/TeamspeakBuildCache.class.php#L46

But I wonder why this code the called two times ....
