### ISSUE TITLE
Field Summ

### ISSUE THREAD

**Issue by bornhaeusser** [jkroepke/2Moons#231]
The Summary of the Building is on the Mainplanet wrong. (Each Player) the colonys Summary is right,

![image](https://cloud.githubusercontent.com/assets/6609040/16294886/af8e7684-3923-11e6-8668-f7f21e72e1d1.png)

**Comment by jkroepke** [comment]
Did you add or remove bulidings via admin panel?

**Comment by bornhaeusser** [comment]
not on each player. (Did they not be listet if they come from admin menue?)

**Comment by OzanKurt** [comment]
maybe one of the buildings doesnt require space?

**Comment by jkroepke** [comment]
Can not verify this.
