### ISSUE TITLE
Resource production in vacation mode

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#233]
Hello resource production stops visualy when you are in vmode but when you get out of vmode some time after that even with that line, you get the production of the last time your planet was updated and not with that new timestamp

https://github.com/jkroepke/2Moons/blob/master/includes/pages/game/ShowSettingsPage.class.php#L151

**Comment by Hilarious001** [comment]
fixed

**Comment by jkroepke** [comment]
How?

**Comment by bornhaeusser** [comment]
is still happening.
