### ISSUE TITLE
Sql Injection Possibilities

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#239]
Hello @jkroepke 

Just to let you know that the ally_events of the game are sensible to sql injections
https://github.com/jkroepke/2Moons/blob/master/includes/pages/game/ShowAlliancePage.class.php#L756

How to proceed, go to alliance page, admin edit page, right click on a mission event, change the value with 1');select*from uni1_users;

Regards

**Comment by Hilarious001** [comment]
and you will get an error that say you have an error with your sql server please verify the right syntax, and this mean its sql injectable

Regards

**Comment by OzanKurt** [comment]
Good job!

**Comment by Hilarious001** [comment]
@OzanKurt still runining a game as you are active on github ?

Regards

**Comment by jkroepke** [comment]
I got this error:

```
Message: Invalid argument supplied for foreach()
File: /includes/classes/HTTP.class.php
Line: 81
URL: http://localhost/2moons/game.php?page=alliance&mode=admin&send=1&events=1%27);select*from%20uni1_users;
PHP-Version: 7.0.9-1+deb.sury.org~xenial+1
PHP-API: fpm-fcgi
MySQL-Cleint-Version: mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $
2Moons Version: 1.7.git
Debug Backtrace:
#0 /includes/classes/HTTP.class.php(81): errorHandler(2, 'Invalid argumen...', 'FILEPATH ...', 81, Array)
#1 /includes/classes/HTTP.class.php(72): HTTP::_quoteArray('1');select*from...', false)
#2 /includes/pages/game/ShowAlliancePage.class.php(756): HTTP::_GP('events', Array)
#3 /includes/pages/game/ShowAlliancePage.class.php(735): ShowAlliancePage->adminOverview()
#4 /game.php(57): ShowAlliancePage->admin()
#5 {main}
```

Did you get the same?

**Comment by jkroepke** [comment]
I can not get an error. I can not verify this issue on my game.

**Comment by Hilarious001** [comment]
i tried it on different games with the owners permission and each time got the error.
if this can help, it has been tested and valid on all games having this module available
[URL=http://www.hostingpics.net/viewer.php?id=946827Sanstitre.png][IMG]http://img15.hostingpics.net/pics/946827Sanstitre.png[/IMG][/URL]
[URL=http://www.hostingpics.net/viewer.php?id=941219dzd.png][IMG]http://img15.hostingpics.net/pics/941219dzd.png[/IMG][/URL]

**Comment by OzanKurt** [comment]
@Hilarious001 Sadly, no. I am currently employed and don't have time between school and job.

**Comment by jkroepke** [comment]
Please verify this issue here: http://jan.creativesandbox.de/2moons

**Comment by lilmnm-kamikaze-** [comment]
@jkroepke i was also able to get it to show as well from the link you just provided. 

I made an alliance named test and used firebug to edit the value from 1 to 1');select*from uni1_users; and then saved then i get the error when ever i try to view the alliance page [http://jan.creativesandbox.de/2moons/game.php?page=alliance](http://jan.creativesandbox.de/2moons/game.php?page=alliance)

**Comment by jkroepke** [comment]
Thanks.

**Comment by jkroepke** [comment]
Should be fixed right now.

I added a new Modi for `HTTP::_GP`

If you expect an array with numeric elements, you can use array(0) as 2nd parameter.

**Comment by Hilarious001** [comment]
Thanks i will test it and will keep u updated

Regards
