### ISSUE TITLE
Error in costresource function

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#241]
Hello @jkroepke this function need to be reviewed as you are requesting the price for a building that has already been build instead of the price of the next level
https://github.com/jkroepke/2Moons/blob/master/includes/pages/game/ShowBuildingsPage.class.php#L320

$LevelToBuild = $levelToBuild	= $PLANET[$resource[$Element]]; 

In that case we already have that level build so it should go for the next level with a $LevelToBuild+1

Regards

**Comment by jkroepke** [comment]
I will look into this issue if i get some time.

**Comment by jkroepke** [comment]
Hi,

I found the problem. The function is working fine. The problem are the wrong values in the vars db.

Current, the cost901, cost902 and cost903 values are for level 1, but should be for level 0.

An example:
calculation: (base value in db) * (factor value in db) ^ (level to build)

Current values in vars db for metalmine:
metal: 60
crystal: 15
factor: 1,5

Calculation for lv 1: 

Metal: 60 * 1,5 ^1 = 90
Crystal; 15 * 1,5 ^1 ~ 22

According to [owiki](http://owiki.de/index.php/Metallmine), this are the values for lv 2.

Expected values in vars db for metalmine:
metal: 40
crystal: 10
factor: 1,5

Calculation for lv 1: 

Metal: 40 * 1,5 ^1 = 60
Crystal; 10 * 1,5 ^1 = 15

According to [owiki](http://owiki.de/index.php/Metallmine), this are the values for lv 1.


To resolve this issue, we have to change the values the database. 

We also add a +1(#245, #246) to all related build pages.

**Comment by Hilarious001** [comment]
Don't know where to post that code, but this should resolve your database values [untested not home quickly coded but should be ok!]


```
<?php

define('MODE', 'INGAME');
define('ROOT_PATH', str_replace('\\', '/',dirname(__FILE__)).'/');
set_include_path(ROOT_PATH);

require 'includes/common.php';

$needChanged = array(1,2,3,4,6,12,14,15,21,22,23,24,31,33,34,44,106,108,109,110,111,113,114,115,117,118,120,121,122,123,124,131,132,133,199);
foreach($needChanged as $modified){
	$NewValueMetal 		= $pricelist[$modified]['cost']['901'] / 1.5;
	$NewValueCrystam 	= $pricelist[$modified]['cost']['902'] / 1.5;
	$NewValueDeuterium 	= $pricelist[$modified]['cost']['903'] / 1.5;
	$sql	= 'UPDATE %%VARS%% SET cost901 = :cost901, cost902 = :cost902, cost903 = :cost903 WHERE id = :modified;';
	$db->update($sql, array(
		':cost901'	=> $NewValueMetal,
		':cost902'	=> $NewValueCrystam,
		':cost903'	=> $NewValueDeuterium,
		':modified'	=> $modified
	));
}
?>
```

**Comment by Hilarious001** [comment]
Updated the code due to factor error

Regards

**Comment by jkroepke** [comment]
```
UPDATE uni1_vars SET
cost901 = cost901 / factor,
cost902 = cost902 / factor,
cost903 = cost903 / factor
WHERE elementID IN (1,2,3,4,6,12,14,15,21,22,23,24,31,33,34,44,106,108,109,110,111,113,114,115,117,118,120,121,122,123,124,131,132,133,199);
```

currently, I'm working on a generic solution to apply database patches semi automatic.

**Comment by Hilarious001** [comment]
yup didnt though about that solution,
but i was thinking for existing games like mine or all other games, they can have specific buildings and techs created by them self ? so i was wondering, if it wasnt better to use something like that ? anyway all functions would be fine, you hve the choose :palm_tree: 


```
UPDATE uni1_vars SET
cost901 = cost901 / factor,
cost902 = cost902 / factor,
cost903 = cost903 / factor
WHERE class < 200;
```

**Comment by jkroepke** [comment]
This issue can be resolved. I added a migration to upgrade the database semi automatic
