### ISSUE TITLE
[Help Request] Execute JS after succes Ajax Call

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#242]
Hello everyone, since there is no real forum, i though i could maybe ask it here ?
How could i execute a js script after a succesfull ajax call,

This would be my js to be exectued after the js call, the js itself is a simple echo actualy but it don't echo at all :p

`<script type="text/javascript">apprise("<b>Some text here</b>", {'maxWidthWindow' : 400, 'alert' : true});</script>`

In case of this does nothing
`success:function(e){e}`

This echo the script i am asking to be executed in an alert box so i know it reconize my echo already
`success:function(e){alert(e)}`

**Comment by jkroepke** [comment]
Why you do not use jQuery? Its much easier to do things in JS.

**Comment by Hilarious001** [comment]
`creerEquipe:function(){apprise(JS_LNG_103,{maxWidthWindow:450,input:!0,widthInput:150},function(e){$.ajax({type:"POST",url:"game.php?page=population&mode=flotte&setupName="+e,data:$("#form_creer_equipe").serialize(),success:function(e){location.reload()}})})}`

i currently added location.reload as i cant echo my js code i want to send.

**Comment by jkroepke** [comment]
Sorry, I can't understand you.

**Comment by lilmnm-kamikaze-** [comment]
he is saying he would like to run a js function in the success:functin(e){} section after the ajax call. which is very simple if you are trying to echo a response. I use this on my mobile app for my server

`$.ajax({
		url: site + page,
		cache: false,
		dataType: 'html',
		data: ({toServer1 : userInput1 toServer2 : userInput2}),
		type: POST,
		success: function(response){
			$(#content).html(response);
		},
		error: function(xhr, ajaxOptions, thrownError){
			//alert("xhr: " +xhr+ "  ajaxOptions: "+ajaxOptions+"   thrownError: "+thrownError);
			//oh no error
		}`

That echos your response from the successful ajax call and parses it to something like

`<div id="content"></div>`

that is located on your page.

hope this is what you are asking if not i am sorry

**Comment by Hilarious001** [comment]
Hello, this is a basic function but thanks atleast for the reply, but that are codes i know from my head.
I have a mod where players create their own ships, give it an image a name, wapeon, armor and shields stats and the price and the techs are autocalculated in function of what their different created ships are equiped.
What  i need is to response a javascript code.

What @lilmnm-kamikaze- replied is a simple html text echo, what i would need is to echo this and that it is also run the code, when its called in the response.

`<script type="text/javascript">apprise("<b>Some text here</b>", {'maxWidthWindow' : 400, 'alert' : true});</script>

I can use alert with a html echo but thats not really beautyfull.
my js that i want to echo is showing like this (with the script code above)

<a href="http://www.hostingpics.net/viewer.php?id=132389Sanstitre.png"><img src="http://img4.hostingpics.net/thumbs/mini_132389Sanstitre.png" alt="Heberger image" /></a>

**Comment by lilmnm-kamikaze-** [comment]
you could look into this then and see if it fits into what you need

http://www.w3schools.com/jquery/ajax_getscript.asp

**Comment by jkroepke** [comment]
Can I close it?

I open a Q&A board for questions. See https://www.codewake.com/p/2moons

**Comment by Hilarious001** [comment]
Just to add the answer to echo and execute js script as a response on a js call, i had to add in the php file
header('Content-Type: text/javascript');

**Comment by lilmnm-kamikaze-** [comment]
I would lie to see how you have t set up if you dont mind. I am interested in useing something similar on my server and couldnt find a good way to get it to work.

**Comment by Hilarious001** [comment]
Hello simply in my file in the root folder

```
<?php
define('MODE', 'JSON');
define('ROOT_PATH', str_replace('\\', '/',dirname(__FILE__)).'/');
set_include_path(ROOT_PATH);
require 'includes/common.php';

if($failed){
header('Content-Type: text/javascript');
echo 'location.reload()';
}else{
//context text html here
echo 'good job';'
}
```
its a simpe example but working

**Comment by lilmnm-kamikaze-** [comment]
Ahh i see.

I used this as a simple way to run Javascript out side of the jQuery i run from my mobile phone app when.

```
echo '<script type="text/javascript">jQT.goBack();//or other functions</script>';
```
