### ISSUE TITLE
[Info] Get A Game - Create your personal space game !

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#251]
Hello, I'm reusing a system to launch different type of game like Antaris, xterium and another in development and wondered if it could interest people to use such services.

* The Antaris and Xterium platforms were completely recoded and review.

In short terms, what is this system. after registering on the portal. you have the ability to launch a quality game tested for months and months by hundred of players.
The games in question comes with a Control Panel© fully dedicated and redesigned for the administration of the chosen game.

No monthly fees or management skills at the server level are required because everything is directly hosted on our dedicated quality servers.

The game is made available to the subscriber with one language defined during the registration process, 
It is for sure possible to add more language to your game with extensions for the work provided

You'll even be able immediately to win money with your game. You start with a 60% rate that can climb up to a 75% depending on the number of purchases made on your game over a period of 30 days.

€10* of welcome bonus is offered to the first 100 registered (*Withdrawal from €25)
For more information, you can add me on Skype [xterium.support]. We expect the launch of the first game by september 2016. We are open to discussions and questions each evening after 22h30 CET.

The main feature, being our automated and customised admin panel, you can view here some samples of it. it has never been so easy to manage a game

<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="http://img4.hostingpics.net/pics/4206354449.png" border="0" alt="Hebergeur d'image" /></a>
<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="http://img4.hostingpics.net/pics/5474394450.png" border="0" alt="Hebergeur d'image" /></a>
<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="http://img4.hostingpics.net/pics/5650344451.png" border="0" alt="Hebergeur d'image" /></a>

**Comment by OzanKurt** [comment]
Please don't advertise.

**Comment by OzanKurt** [comment]
This place is called issues.

**Comment by OzanKurt** [comment]
People who doesn't code wont even check the issues section in GitHub.

**Comment by Hilarious001** [comment]
Losing time to login just to say that when you dont take time to login and respond to issues. o.O 

People are really weird here. Can be closed then. i am out of github from now on 
If some one need fast and effective help. Dont hesitate to add me Skype [xterium.support]

Bye

**Comment by OzanKurt** [comment]
Please go, this is a developers community, nobody really cares about the money you want.

**Comment by Hilarious001** [comment]
Lol i dont really see what you are doing here if its a developers community ? i don't see you responding or giving help. You don't have to respond also.
Support is over here for me, stay with your bugs :)
PS: If some one need fast and effective help. Dont hesitate to add me Skype [xterium.support]

**Comment by OzanKurt** [comment]
Poor money dog.

**Comment by jkroepke** [comment]
> This place is called issues.

Correct. Sorry.
