### ISSUE TITLE
When cancelling a building, you only get 50 % of the ressources refunded

### ISSUE THREAD

**Issue by sp33d86** [jkroepke/2Moons#254]
Happened multiple times now.
So, I think this is persistent.
I think I remember that I already cancelled buildings in the past and the ressources were correctly refunded. But I'm not 100 % sure.
In the past few days I cancelled multiple buildings and at least two times I got the wrong refund.
This also happened to another player.
Maybe this is kind of depending on the game speed setting. Because that's something we changed in the past...

**Comment by Hilarious001** [comment]
Hello,

Its normal, you will allways get 50% returned in case of you cancel a building in construction. its part of the code, you can still change it.
This ticket should be closed.

**Comment by jkroepke** [comment]
Correct.
