### ISSUE TITLE
Question about languages

### ISSUE THREAD

**Issue by HappinessPK** [jkroepke/2Moons#261]
I'm trying to translate this into Norwegian but i have no idea how i should get the changes in the game. I've been messing around in the files looking for an answer a while now and would greatly appreciate if i could get some directions with this.

**Comment by jkroepke** [comment]
Hi, adding new languages is easy as touch.

1. Copy a base language. 
copy language/en language/<your lang>

Modify the LANG.cfg in your new language directory.

Login into the admin panel and clear the cache. Now you can select the new language.

Then you can begin to translate all the files.

**Comment by HappinessPK** [comment]
Okey, thank you very much.
