### ISSUE TITLE
Remind/Reset password functionality is missing

### ISSUE THREAD

**Issue by sunchaser68** [jkroepke/2Moons#262]
A user that forgot a password cannot reset or request a reminder.

**Comment by jkroepke** [comment]
Because?

**Comment by HappinessPK** [comment]
The functionality is there. But it lacks a button that guides you there. Try going to <domain>.com/index.php?page=lostPassword to find it.

**Comment by sunchaser68** [comment]
Ok, The button appeared after i set Enable Mail: YES in administration panel.

**Comment by jkroepke** [comment]
Otherwise, 2Moons cant send mails. I know, there is no real documents for this issue.

sunchaser68 <notifications@github.com<mailto:notifications@github.com>> schrieb am Mi., 31. Aug. 2016, 09:10:

Ok, The button appeared after i set Enable Mail: YES in administration panel.
