### ISSUE TITLE
Wrong data in Alliance message

### ISSUE THREAD

**Issue by sunchaser68** [jkroepke/2Moons#265]
I received a message from an Ally. From and Date fields contains strange data.

![screenshot_20160906 220113](https://cloud.githubusercontent.com/assets/19151698/18316265/3cfadddc-751a-11e6-923b-124348b4362e.png)

PS: Sorry but i am new to GIT... what happens now? If i fix it how what's the procedure? Thanks

**Comment by jkroepke** [comment]
Hi!

thanks you submitting a bug here.

> Sorry but i am new to GIT... what happens now? If i fix it how what's the procedure?
I dont know, if its good. But you can try: https://www.youtube.com/watch?v=YTbRzhQju4c . Dont be confused, in the video you can see an old version of github.

Cheers 
Jan

**Comment by sunchaser68** [comment]
I have the fix ready but if i click New Pull Request from your branch, it doesn't let me.
