### ISSUE TITLE
Rapidfire

### ISSUE THREAD

**Issue by terassiel** [jkroepke/2Moons#271]
Rapifire is currently a complete mess!
Currently it is treated as a additive constant meaning that a ship gets all its rapidfire shots at once for all ship types it has rapidfire on. Some examples : 
1 Deathstar Vs 1 Deathstar results in 1 shot each per round;
1 Deathstar Vs 1 Solar sattelite (RF 1250), 1 Spyprobe (RF 1250), 1 Deathstar results in a total of 2501 Shots
This means that a player who includes several types of ships actually worsens the combat result for himself up to a point where a small fleet can take down much bigger fleets just because the bigger fleet includes ships with enemy rapidfire.

I actually made a succesfull re-write of the whole battlescript including explosion flags and ogame-like rapidfire but that solution is useless. Reason beeing that this type of rapidfire creats a shit ton of simulations/calculations that cant be processed in a reasonable time on any "normal" type of server. 

Does anybody have a idea on how to addres this problem?

**Comment by jkroepke** [comment]
The current rapid system does not work. Instead simulate every single unit, it calculate types. That's why you have unexpected results.

I wrote the system in php. Checkout this: https://gist.github.com/jkroepke/7d2499966b0358daa940

But its really inefficient.

**Comment by jkroepke** [comment]
Otherwise, let discuss it here: https://gitter.im/2MoonsGame/Lobby
