### ISSUE TITLE
Security probleme and bug when deleting planet

### ISSUE THREAD

**Issue by BigTwoProduction** [jkroepke/2Moons#273]
Hello,

I return back ! :) So I look at my error log and I found a big problem I think... 

When a player try to delete his or one planet I a*have an error, but in fact this is not the main noise!
Then password of player is clairly write in URL !

`[03-Nov-2016 13:47:25] WARNING: "Creating default object from empty value"^M
373 File: /var/www/html/xnovareborn/includes/pages/game/ShowOverviewPage.class.php | Line: 394^M
374 URL: http://www.big-two.tk/xnovareborn/game.php?page=overview&mode=delete&password=********* | Version: 1.8.git^M
375 Stack trace:^M
376 #0 /includes/pages/game/ShowOverviewPage.class.php(394): errorHandler(2, 'Creating defaul...', '/var/www/html/x...', 394, Array)
377 #1 /game.php(57): ShowOverviewPage-&gt;delete()
378 #2 {main}^M`

So want do your think about that ?

Best regards,
BigTwoProduction.

**Comment by jkroepke** [comment]
Hi!

welcome back!

> So want do your think about that ?
It must be fixed!

Cheers
Jan

**Comment by BigTwoProduction** [comment]
Hello,

I put this fix and I confirm that work great! Good jobs!!! :)

Best regards,
Jordan.

**Comment by jkroepke** [comment]
Since I have a working test environment, the fixes should be almost work. :D
