### ISSUE TITLE
Alliance Have A problem

### ISSUE THREAD

**Issue by sromantr** [jkroepke/2Moons#275]
Message: Incorrect Select Query
File: /includes/classes/Database.class.php
Line: 173
URL: http://asgard.byethost3.com/game.php?page=alliance&mode=admin&action=detailApply&id=2
PHP-Version: 5.6.23
PHP-API: apache2handler
MySQL-Cleint-Version: mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
2Moons Version: 1.7.2633
Debug Backtrace:
#0 /includes/pages/game/ShowAlliancePage.class.php(1125): Database->selectSingle('/n/t/tSELECT/n/t/t/tr....')
#1 /includes/pages/game/ShowAlliancePage.class.php(776): ShowAlliancePage->adminDetailApply()
#2 /game.php(68): ShowAlliancePage->admin()
#3 {main}

**Comment by jkroepke** [comment]
You are using a very old version of the game. Please use the latest master https://github.com/jkroepke/2Moons/archive/master.zip
