### ISSUE TITLE
Lost of resource

### ISSUE THREAD

**Issue by Hilarious001** [jkroepke/2Moons#278]
Hello @jkroepke 

We are currently encountering a new error without having any clue how this can happen, players are deploying resource and sometimes it appaer some players dont have their resource when it lands.

So i created a log file to see what happen on the database values when fleets lands by selecting the resource before the drop of and making a new select of it after they have been dropped. You can see the query that need to be executed, the values of the resource before it landed and the value of the resource after it landed (the database provide those values each time with new select queries) 

So the log comfirm they where present on the planet, but after that it seems they disapaer...

`01-22-2017 09:33:44 IP_ADRESS_PLAYER
SQL: UPDATE %%PLANETS%% as p, %%USERS%% as u SET
		p.`battle_ship` = p.`battle_ship` + :battle_ship,
		p.`metal` = p.`metal` + :metal,
		p.`crystal` = p.`crystal` + :crystal,
		p.`deuterium` = p.`deuterium` + :deuterium,
		u.`darkmatter` = u.`darkmatter` + :darkmatter
		WHERE p.`id` = :planetId AND u.id = p.id_owner;
PARAMS: Array
(
    [:metal] => 0
    [:crystal] => 0
    [:deuterium] => 13899968
    [:darkmatter] => 0
    [:planetId] => 10502
    [:battle_ship] => 261441
)

Default: Array
(
    [metal] => 132859012278.000000
    [crystal] => 167612514369.000000
    [deuterium] => 139700327714.500000
)

RESULT: Array
(
    [metal] => 132859012278.000000
    [crystal] => 167612514369.000000
    [deuterium] => 139714227682.500000
)`

**Comment by zbdermighty** [comment]
Hm is it possible to do it so that this Problem occurs or is it random? So i could may look for it.

**Comment by lilmnm-kamikaze-** [comment]
we had this problem with our game and it would happen when the planet was updated right when the fleet landed and the res would be overwritten  with the planet update.

**Comment by Hilarious001** [comment]
Hm is it possible to do it so that this Problem occurs or is it random? So i could may look for it.
=> no there isnt its purly randomly, some players even never had this error; it are mostly the same players.

we had this problem with our game and it would happen when the planet was updated right when the fleet landed and the res would be overwritten with the planet update.
=> Hmm i will disable the planet updater from planetresudpate class when fleets land then. to see if it change something, i can probably use the private disableeco feature for this

Regards

**Comment by jkroepke** [comment]
Otherwise have to enable (and code) a audit log for all sql queries to identify to problem.

Do you use MyIASM oder InnoDB as Engine? You can get it with `SHOW CREATE TABLE uni1_users;` and look at the ENGINE parameter

**Comment by Hilarious001** [comment]
Hello => MyISAM

**Comment by jkroepke** [comment]
Yeah, MyISAM is pretty old and does not have transactions like InnoDB. 2Moons still enforce MyISAM but it's not recommend in 2017. 

How ever write an audit log for all query should be easier to find the gap.

**Comment by zbdermighty** [comment]
Why disabling the planet updater? Just write 3 Lines that the planet updater shouldnt update the last 3-5 Seconds before they land on that planet ;)

**Comment by lilmnm-kamikaze-** [comment]
we used MyISAM but changed to InnoFB and did some other fixes to the database lib and we didnt get it as much as we used to but we had a random case the other day. it also effected when something finished building it would reset to level 1 if a fleet would land right when the tech or building finished or the planet was updated by switching to it from a different planet.

We have yet finished testing for what exactly happens or for a fix before we have to rewrite every db query like for transactions.

zdber - Planets update when you switch to the planet then when you access the build pages.

**Comment by Hilarious001** [comment]
Why disabling the planet updater? Just write 3 Lines that the planet updater shouldnt update the last 3-5 Seconds before they land on that planet ;)

Why writing 3 lines while you might do it in 3 words ? since their is a function available in 2moons for this purpose that simply disable the update of the planets when the file is loaded but that start again to update when it finished to load ?

I am thinking to call that function in the class/missionfunction file. this will then be called in all mission files and will end when the mission file is finished, this way it will not update the planet when it restorefleet or storegoodstoplanet as you disable the economie, at least its what i think, i can be wrong

Regards

**Comment by zbdermighty** [comment]
Oh i thought about something that you make a variable which includes the next arrival time on that Planet and if its below 5 seconds, you deactivate it.
if($nextLanding > TIMESTAMP - 5)
       Function();

**Comment by jkroepke** [comment]
Stop the hacks please.

**Comment by Hilarious001** [comment]
I didn't follow the last comment :/

**Comment by zbdermighty** [comment]
Any news Hilarious001?

**Comment by jkroepke** [comment]
I will look into this issue the weekend. Maybe I will create a public chat room to discuss this issue.

**Comment by Hilarious001** [comment]
I close this, error is still persistent, didnt found the problem about it

**Comment by jkroepke** [comment]
I can only fix error, if there are reproducible for me.

**Comment by Hilarious001** [comment]
Hello,

No problem i know its not easy to reproduce, since even at our game it happen randomly, i have 30 free days in july, i will have more time to concentrate on it. if i can fix it then i will post pr

Regards

**Comment by jkroepke** [comment]
Maybe the logging of all UPDATE queries maybe be help
