### ISSUE TITLE
Construction time.

### ISSUE THREAD

**Issue by sandub** [jkroepke/2Moons#286]
Construction time!
On some construction at a level higher than necessary during construction upgrate it lasts many days. Some even years. Being a game I do not think anyone will stand 10 years to upgrate a building
Solar Power plant at level 64 if needs 3958d 17h 08m 55s.
Should the upgrate to put, and a button for instant finish with a reasonable cost in dark matter. This helps prospective players enrolled late in the game to advance and approach the oldest and participate in wars. What do you think?

PS can make a tax calculation system to be set in admin panel like (tax * level=price)
*****************
Anyone is interested I schedule some modules surcharge

**Comment by lilmnm-kamikaze-** [comment]
why would anyone have a level 64 power plant? it would be better to build sats and the fusion plant.
