### ISSUE TITLE
Installation - checking access permission error

### ISSUE THREAD

**Issue by Ah3n0** [jkroepke/2Moons#287]
During the installation the check of needed access to files and directories goes wrong. 
If I have change the permission step by step. When I finished, check of "includes" and /includes/config.php" failed with not write permission. After changing write permission back read of dir "cache" permission of "includes" and /includes/config.php" passed. But "cache" failed (obviously). changing back, same problem. => can´t continue to step 4 without changing it in url mask.

**Comment by lilmnm-kamikaze-** [comment]
make sure the config.php file has the permissions of 0777

**Comment by jkroepke** [comment]
OS? PHP Version?

**Comment by Ah3n0** [comment]
Using XAMPP 5.6.24-2 on OSX 10.12.3. PHP Version 5.6.24.

I changed config.php to 0777 as required during the installation. 
When everything has the correct permission check of "includes" failed (but hast the correct permission). If I change the permission of "includes" "cache" works. Otherwise an permission to write error appears. 
But! After it still show me an permission error although everything is correct I can skip by typing 3 als next step to url and installation works. 
I guess it is just an display error / check error.

**Comment by jkroepke** [comment]
Did you install 2Moons inside you home directory? If yes, you can try somethink like /tmp ?

Mac is using ACLs sometimes and maybe PHP is confused here.

Also please try PHP 7.x, if its possible.

From the code side, I don't see any logical error there.

**Comment by Ah3n0** [comment]
I´ve tried it again with the lates version of xampp (PHP 7.1.1; XAMPP 7.1.1. )
Unfortunately, there is the same situation.

[See pictures](https://www.dropbox.com/sh/36jzr01206kk4pz/AAA7kwOuHr8_g_xNwA7Ixohja?dl=0)

I installed it inside htdocs and used an other dir called moon (.../htdocs/moon/<all stuff>)

**Comment by jkroepke** [comment]
Should be fixed w/ 5cf1e868ddaf2b98155d7e107ff07f3f9c89b6ef
