### ISSUE TITLE
USER ERROR

### ISSUE THREAD

**Issue by sandub** [jkroepke/2Moons#288]
USER ERROR
Message: Call to undefined function getUniverse()
File: /includes/common.php
Line: 108
URL: http://antaris.esy.es/
PHP-Version: 7.0.16
PHP-API: litespeed
MySQL-Client-Version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
2Moons Version: UNKNOWN
Debug Backtrace:
#0 /index.php(35): require()
#1 {main}

**Comment by wumix** [comment]
This isn't 2moons

sandub <notifications@github.com> schrieb am So., 19. März 2017, 20:01:

**Comment by jkroepke** [comment]
https://github.com/jkroepke/2Moons/blob/master/includes/common.php#L108

Please use the latest version of 2moons.
