### ISSUE TITLE
[Suggestions] - [Modules] - Natural moon, gas giant and more

### ISSUE THREAD

**Issue by Quarior** [jkroepke/2Moons#291]
I suggested this in a module because if people want to disable, will be easy.

I want to know if you planned to add for natural spawn of gas planet (there already image) and natural moon generation with several types like the planets but moon may be have atmosphere so you can build construction like on planets (and on moons) and moons without atmosphere just like now moon construction.

Also for gas giant, construction can may be like planets but haven't mine of metal and crystal.

After this if possible, may be create a another module for create world-ship.

Good luck and continuation.

**Comment by Hexeus** [comment]
Very good idea. I am dreading to have to make an account, use it as a bot, and spawn it with planets and moons.

**Comment by ogamemaster** [comment]
yes possible to build :)

**Comment by jkroepke** [comment]
Hi! You idea is interesting. 

Its not planned to add this features. In my option a bot framework should not included to this game.

I have start write a bot in 2011. Its not full feature. Maybe there are some inspirations for you. 

https://www.dropbox.com/s/le8uwdl98i0q2mp/BOT.zip?dl=1
