### ISSUE TITLE
Jumpgate Settings

### ISSUE THREAD

**Issue by Hexeus** [jkroepke/2Moons#299]
I am looking through the settings in the ACP, and there is no option to change the Jumpgate wait time. Could it be possible that it be added in the future?

**Comment by jkroepke** [comment]
There is a setting "Portal" on the Universe Page. Thats the setting you want.

The label is strange.

**Comment by Hexeus** [comment]
Oh, I totally over looked that, I thought "Portal" was for the news settings.
 Thanks!
