### ISSUE TITLE
[Game breaking] Cost and building time reduction glitch.

### ISSUE THREAD

**Issue by Takfar** [jkroepke/2Moons#313]
First of all, it only works when the building queue is activated.

steps : 

0. The building queue is empty
1. Put something in the building queue ( anything, preferably cheap )
2. Put something in the building queue while the first building is still in queue
3. Cancel the ongoing building in the queue
4. The price, and the time to craft the next building in the queue are reduced

It's working, I tried it on my live and local server.

**Comment by jkroepke** [comment]
Can you re-test it w/ the patches in https://github.com/jkroepke/2Moons/pull/314

**Comment by Takfar** [comment]
The glitch is still working.

**Comment by Takfar** [comment]
any idea ?

**Comment by jkroepke** [comment]
No. It's still on my todo list. Just some time issues.

**Comment by jkroepke** [comment]
Done

**Comment by jgalat** [comment]
This issue is also at the research queue. 
It uses the current level at the planet to calculate the cost. I'm already making a pull request with the same fix applied to research queues.

**Comment by jgalat** [comment]
Messed up last pull request, switched from the wrong branch... Sorry.
Now last one is right.
