### ISSUE TITLE
[Combat bug] Hull tanking is not working as intended.

### ISSUE THREAD

**Issue by Takfar** [jkroepke/2Moons#320]
To destroy a ship, you need to deal the hull amount of in damage.

For example, to destroy a dearth star, you need to deal 900K damage to the dearth star.

But every turn in a battle phase, the hull is restored to the max amount ( in 2moons, not in official ogame )

- On official ogame, you need atleast 60 destroyers to destroy a single DS in 5 turns.

- On 2moons, you can't destroy a single DS without 300 destroyers, because only 300 destroyers are able to one shot a DS in 1 turn.

So combat is not working as intended because, like I said, every turn, the hull is fully restored to max

**Comment by jkroepke** [comment]
This game doesn't have a combat engine like ogame does. The Problem ist that the ogame engine does much more resources and doesnt scale in php well.

Maybe you have some luck with https://github.com/jstar88/opbe

**Comment by Takfar** [comment]
Do you think its possible to reduce the maximum hp of a specific ship ?
