### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ogamemaster** [jkroepke/2Moons#324]
Issue: SQL Error: Out of range value for column 'fleet_resource_crystal' at row 1

Query Code: UPDATE uni1_fleets SET `fleet_resource_metal` = '4.79287544308E+16', `fleet_resource_crystal` = '-4.42998180092E+16', `fleet_mess` = '1' WHERE `fleet_id` = 1115760;UPDATE uni1_fleet_event SET time = 1502988781 WHERE `fleetID` = 1115760;
File: /includes/classes/class.Database.php (Line 255)
PHP: Version 5.6.31 [ litespeed ]
MySQL: mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $

Debug Track:
#0 /includes/classes/class.MissionFunctions.php(73): Database->multi_query('UPDATE uni1_fle...')
#1 /includes/classes/missions/MissionCaseRecycling.php(92): MissionFunctions->SaveFleet()
#2 /includes/classes/class.FlyingFleetHandler.php(82): MissionCaseRecycling->TargetEvent()
#3 /includes/FleetHandler.php(40): FlyingFleetHandler->run()
#4 /includes/common.php(104): require('FILEPATH ...')
#5 /game.php(11): require('FILEPATH ...')
#6 {main}

**Comment by Hilarious001** [comment]
You have to increase values in your database, 2moons is designed to work on slow speed universe, if you want to use it on hight speed universe, then modify your database

**Comment by jkroepke** [comment]
You reached the maximum thats currently supported.
