### ISSUE TITLE
bei ansicht der Galaxy

### ISSUE THREAD

**Issue by Lyon-bln** [jkroepke/2Moons#326]
Message: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #26 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'lyon_uni2.s.total_points' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Query-Code:SELECT SQL_BIG_RESULT DISTINCT p.galaxy, p.system, p.planet, p.id, p.id_owner, p.name, p.image, p.last_update, p.diameter, p.temp_min, p.destruyed, p.der_metal, p.der_crystal, p.id_luna, u.id as userid, u.ally_id, u.username, u.onlinetime, u.urlaubs_modus, u.banaday, m.id as m_id, m.diameter as m_diameter, m.name as m_name, m.temp_min as m_temp_min, m.last_update as m_last_update, s.total_points, s.total_rank, a.id as allyid, a.ally_tag, a.ally_web, a.ally_members, a.ally_name, allys.total_rank as ally_rank, COUNT(buddy.id) as buddy, d.level as diploLevel FROM uni1_planets p LEFT JOIN uni1_users u ON p.id_owner = u.id LEFT JOIN uni1_planets m ON m.id = p.id_luna LEFT JOIN uni1_statpoints s ON s.id_owner = u.id AND s.stat_type = 1 LEFT JOIN uni1_alliance a ON a.id = u.ally_id LEFT JOIN uni1_diplo as d ON (d.owner_1 = 0 AND d.owner_2 = a.id) OR (d.owner_1 = a.id AND d.owner_2 = 0) AND d.accept = 1 LEFT JOIN uni1_statpoints allys ON allys.stat_type = 2 AND allys.id_owner = a.id LEFT JOIN uni1_buddy buddy ON (buddy.sender = 1 AND buddy.owner = u.id) OR (buddy.sender = u.id AND buddy.owner = 1) WHERE p.universe = 1 AND p.galaxy = 1 AND p.system = 1 AND p.planet_type = 1 GROUP BY p.id;
File: /includes/classes/Database.class.php
Line: 123
URL: http://uni2.jango-online.de/game.php?page=galaxy
PHP-Version: 7.0.22-0ubuntu0.16.04.1
PHP-API: fpm-fcgi
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/classes/Database.class.php(190): Database->_query('SELECT SQL_BIG_...', Array, 'select')
#1 /includes/classes/class.GalaxyRows.php(76): Database->select('SELECT SQL_BIG_...', Array)
#2 /includes/pages/game/ShowGalaxyPage.class.php(89): GalaxyRows->getGalaxyData()
#3 /game.php(57): ShowGalaxyPage->show()
#4 {main}

brauche hier eventuell bitte ein SQL befehl. 

```-- Server Info --
Server Infos: Apache
PHP-Version: 7.0.22-0ubuntu0.16.04.1 (fpm-fcgi)
JSON Verfügbar: Ja
BCMath Verfügbar: Nein
cURL Verfügbar: Ja
SafeMode: Nein
MemoryLimit: 128M
MySQL-Client-Version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
MySQL-Server-Version: 5.7.19-0ubuntu0.16.04.1
ErrorLog: includes/error.log (158, Aktiv)
Timezone(PHP/CONF/USER): 2 / 2 / 2
Suhosin: Nein
DB Version: 4

-- Game --
Game Version: 2Moons 1.8.git
Game Addresse: http://uni2.jango-online.de/
Game Pfad: http://uni2.jango-online.de/index.php

Browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
```

**Comment by jkroepke** [comment]
Moin,

versuchs mal hier mit: https://github.com/jkroepke/2Moons/pull/327/files?diff=unified

**Comment by Lyon-bln** [comment]
Danke Dir Jan ;)
