### ISSUE TITLE
Fehler bei Gebäuden

### ISSUE THREAD

**Issue by mcules** [jkroepke/2Moons#328]
Hi zusammen,
ich habe ein Gebäude aus der Schleife gelöscht und bekommen nun folgenden Fehler:

Message: DateTime::setTimestamp() expects parameter 1 to be integer, float given
File: /includes/GeneralFunctions.php
Line: 143
URL: https://www.domain.de/game.php?page=buildings
PHP-Version: 7.0.16-1~dotdeb+8.1
PHP-API: cgi-fcgi
2Moons Version: 1.8.git
Debug Backtrace:
#0 [internal function]: errorHandler(2, 'DateTime::setTi...', 'FILEPATH ...', 143, Array)
#1 /includes/GeneralFunctions.php(143): DateTime->setTimestamp(6.2544273027261E+173)
#2 /includes/pages/game/ShowBuildingsPage.class.php(231): _date('U', 6.2544273027261E+173, 'Europe/Berlin')
#3 /includes/pages/game/ShowBuildingsPage.class.php(271): ShowBuildingsPage->getQueueData()
#4 /game.php(57): ShowBuildingsPage->show()
#5 {main}

**Comment by Hilarious001** [comment]
Can we have the code of that line ?
File: /includes/GeneralFunctions.php
Line: 143

**Comment by lilmnm-kamikaze-** [comment]
Why is setTimestamp() trying to set a time stamp of "6.2544273027261E+173"? that number is not a valid unix timestamp that function uses.

its starting from this line [ShowBuildingsPage.class.php](https://github.com/jkroepke/2Moons/blob/master/includes/pages/game/ShowBuildingsPage.class.php#L231) and thats called from line 272 in the same file as you can see in the backtrace and this line in [GeneralFunctions.php](https://github.com/jkroepke/2Moons/blob/master/includes/GeneralFunctions.php#L143) does not like the invalid timestamp

a valid time stamp would be "1504016378"

**Comment by mcules** [comment]
Good Question, source isn't modified. I only deleted a running building process in the gui.
Nothing in DB nor source changed.

**Comment by Lugon89** [comment]
I got the same problem.

Message: DateTime::setTimestamp() expects parameter 1 to be integer, float given
File: /includes/GeneralFunctions.php
Line: 143
URL: https://www.lugon.de/space/uni2/game.php?page=buildings
PHP-Version: 7.1.11-1+0~20171027135525.10+stretch~1.gbp2e638d
PHP-API: cgi-fcgi
2Moons Version: 1.8.git
Debug Backtrace:
#0 [internal function]: errorHandler(2, 'DateTime::setTi...', 'FILEPATH ...', 143, Array)
#1 /includes/GeneralFunctions.php(143): DateTime->setTimestamp(5.1721724504224E+53)
#2 /includes/pages/game/ShowBuildingsPage.class.php(231): _date('U', 5.1721724504224E+53, 'Europe/London')
#3 /includes/pages/game/ShowBuildingsPage.class.php(271): ShowBuildingsPage->getQueueData()
#4 /game.php(57): ShowBuildingsPage->show()
#5 {main}

**Comment by jkroepke** [comment]
@Lugon89 How to reproduce?

**Comment by mcules** [comment]
Just delete an building out the build queue ;)

**Comment by jkroepke** [comment]
Okay. I do follow steps:

* Build metalmine 1
* build crystalmine 1

* delete metalmine 1

- or -

* delete crystalmine1

work fine without the error.


Its unable to reproduce for me. With you steps.
