### ISSUE TITLE
Hall of Fame bug

### ISSUE THREAD

**Issue by Lugon89** [jkroepke/2Moons#331]
When trying to open the hall of fame, it opens following error.
The server is fresh and there were like 4 battles so far. :/

NOTICE
--
Message: A non well formed numeric value encounteredFile: /cache/templates/de^015c77efe7e101e18ce2c8dfaeaab9d56d019446.page.battleHall.default.tpl.phpLine: 435URL: https://www.lugon.de/space/uni2/game.php?page=battleHallPHP-Version: 7.1.11-1+0~20171027135525.10+stretch~1.gbp2e638dPHP-API: cgi-fcgi2Moons Version: 1.8.gitDebug Backtrace:#0 /cache/templates/de^015c77efe7e101e18ce2c8dfaeaab9d56d019446.page.battleHall.default.tpl.php(435): errorHandler(8, 'A non well form...', 'FILEPATH ...', 435, Array)#1 /includes/libs/Smarty/sysplugins/smarty_template_resource_base.php(128): content_59ff768f0f9ee1_72397966(Object(Smarty_Internal_Template))#2 /includes/libs/Smarty/sysplugins/smarty_template_cached.php(136): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))#3 /includes/libs/Smarty/sysplugins/smarty_internal_template.php(179): Smarty_Template_Cached->render(Object(Smarty_Internal_Template), false)#4 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(199): Smarty_Internal_Template->render(false, 1)#5 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(114): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)#6 /includes/classes/class.template.php(137): Smarty_Internal_TemplateBase->display('extends:layout....')#7 /includes/pages/game/AbstractGamePage.class.php(249): template->display('extends:layout....')#8 /includes/pages/game/ShowBattleHallPage.class.php(86): AbstractGamePage->display('page.battleHall...')#9 /game.php(57): ShowBattleHallPage->show()#10 {main}

**Comment by jkroepke** [comment]
Any chance to get an dump of the topkb and raports table?

**Comment by mimikri** [comment]
at line 18 in page.battlehal.default.tpl
change
` <tr class="day{floor($row.date / 86400)} week{floor($row.date / 604800)}">`
to
` <tr> `
this part causes the error and i didn't found any further use of it so deleting it solved the problem for me.

in show.battlehallpage.class.php "$row.date" is defined like that
`  'date'		=> _date($LNG['php_tdformat'], $data['time'], $USER['timezone'])`
this form can not be divided by something
