### ISSUE TITLE
Recall Mission Hold before it reaches Planet

### ISSUE THREAD

**Issue by terassiel** [jkroepke/2Moons#338]
This part from class.FleetFunctions currently gives a timer  equivelent for a full flight duration if the mission is recalled before it reaches the planet, regardless of how long the fleet was on its way.
		if($fleetResult['fleet_mission'] == 5){
		$fleetEndTime	= ($fleetResult['fleet_start_time'] - $fleetResult['start_time']) + TIMESTAMP;
		}else{
		$fleetEndTime	= (TIMESTAMP - $fleetResult['start_time']) + TIMESTAMP;
		}
Im trying to figure out how to fix it, keep you guys posted

**Comment by terassiel** [comment]
if($fleetResult['fleet_mission'] == 5 && $fleetResult['fleet_mess'] == FLEET_HOLD ){
		$fleetEndTime	= ($fleetResult['fleet_start_time'] - $fleetResult['start_time']) + TIMESTAMP;
		}
		elseif($fleetResult['fleet_mission'] == 5 && $fleetResult['fleet_mess'] == FLEET_OUTWARD ){
		$fleetEndTime	= (TIMESTAMP - $fleetResult['start_time']) + TIMESTAMP;
		}
		else
		{
		$fleetEndTime	= (TIMESTAMP - $fleetResult['start_time']) + TIMESTAMP;
		}


Seems to work, the elseif might be redundant

**Comment by jkroepke** [comment]
Like https://github.com/jkroepke/2Moons/pull/339 ?

**Comment by terassiel** [comment]
Looks good
