### ISSUE TITLE
Problem with backups

### ISSUE THREAD

**Issue by Nusuminat** [jkroepke/2Moons#349]
[error.log](https://github.com/jkroepke/2Moons/files/2437409/error.log)

Hello to you.
I have had a problem with Backups for some time. and it's still blinding this bland. the database agrees with dbtables -> although mine is more extensive than the original one.

Greetings to the team

**Comment by mys** [comment]
Do You have set privileges to `includes/backups` path for `www-data` linux account?
Beware, don't set too much privileges to avoid users download whole database from backup ;)

**Comment by Nusuminat** [comment]
probably rather not ... Server I have on VPS, so the confession is not a bit harder for me to do than on the lan I did ...

**Comment by Nusuminat** [comment]
Problem solved

**Comment by jkroepke** [comment]
@Nusuminat what was the problem?

**Comment by Nusuminat** [comment]
Hello, Jana

I have or maybe I do not have a problem anymore ... The problem was that with a cron or even from the admin panel it was not possible to create a backup.

I solved the problem in this way: chmod -R 777 backups to the directory I gave the .htaccess file
But I do not know if this is a good solution, but only so I will start to copy the database to the VPS server.
