### ISSUE TITLE
Problem login after restoring the database 

### ISSUE THREAD

**Issue by Nusuminat** [jkroepke/2Moons#350]
Hello .
I have a problem because I want to do a database backup.
The database got in but at the time of login it caused such a mistake. Although, in the database, given sesionss was created

Message: session_start(): open(/cache/sessions/sess_bf49i1fqn4uq4n8m8vbn537a95, O_RDWR) failed: Permission denied (13)
File: /includes/classes/Session.class.php
Line: 138
URL: http://192.168.2.8/game.php
PHP-Version: 7.0.32-0ubuntu0.16.04.1
PHP-API: apache2handler
2Moons Version: 1.8.git
Debug Backtrace:
#0 [internal function]: errorHandler(2, 'session_start()...', 'FILEPATH ...', 138, Array)
#1 /includes/classes/Session.class.php(138): session_start()
#2 /includes/common.php(114): Session::load()
#3 /game.php(24): require('FILEPATH ...')
#4 {main}
here is the line of code:
/**
	 * Wake an active session
	 *
	 * @return Session
	 */

	static public function load()
	{
		if(!self::existsActiveSession())
		{
			self::init();
			session_start(); <--- it breaks the bland here
			if(isset($_SESSION['obj']))
			{
				self::$obj	= unserialize($_SESSION['obj']);
				register_shutdown_function(array(self::$obj, 'save'));
			}
			else
			{
				self::create();
			}
		}

		return self::$obj;
	}

**Comment by Nusuminat** [comment]
Problem has been solved ;) ...

**Comment by jkroepke** [comment]
File permissions, yeah
