### ISSUE TITLE
Error in link

### ISSUE THREAD

**Issue by spartaelcid** [jkroepke/2Moons#351]
Hello, 

when i try yo click the image " 2moon" in the top left they return this error:
**USER ERROR
Message: Call to undefined function mb_strlen()
File: /includes/libs/Parsedown/Parsedown.php
Line: 144
URL: http://207.180.231.117:8000/game.php?page=changelog
PHP-Version: 7.0.32-0ubuntu0.16.04.1
PHP-API: cli-server
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/libs/Parsedown/Parsedown.php(39): Parsedown->lines(Array)
#1 /includes/pages/game/ShowChangelogPage.class.php(35): Parsedown->text('### v1.8.0/tJan/n...')
#2 /game.php(57): ShowChangelogPage->show()
#3 {main}** 

is not a major error, just minor :D

**Comment by spartaelcid** [comment]
mmm i do all step for the install, but i check it !

**Comment by lilmnm-kamikaze-** [comment]
The php-mbstring is a php exstension. Which is not provided in the repo. You need to install or enable it in your server’s php.ini file. A quick google search will do you the trick

**Comment by jkroepke** [comment]
Wrong?
https://packages.ubuntu.com/xenial/php-mbstring

**Comment by lilmnm-kamikaze-** [comment]
Looks like it but look for one for your php version. Look on php.net. It will have better info

**Comment by jkroepke** [comment]
> PHP-Version: 7.0.32-0ubuntu0.16.04.1

The ubuntu sources are good in this case. There i no need to source the sources directly from php.net

**Comment by lilmnm-kamikaze-** [comment]
I was pointing him there if he had a php version other than php7

**Comment by spartaelcid** [comment]
hello,

i check it, i fix it simply adding as suggested the package in question with the command:

sudo apt-get install php7.0-mbstring

Thanks!
