### ISSUE TITLE
Error with the Chinese language

### ISSUE THREAD

**Issue by spartaelcid** [jkroepke/2Moons#352]
Hello,

if i click on Chinese i have this error, but with other language work!

WARNING
--
Message: explode() expects parameter 2 to be string, array given 			File: /includes/pages/login/ShowIndexPage.class.php 			Line: 57 			URL: http://207.180.231.117:8000/index.php?code=3 			PHP-Version: 7.0.32-0ubuntu0.16.04.1 			PHP-API: cli-server 			2Moons Version: 1.8.git 			Debug Backtrace:#0 [internal function]: errorHandler(2, 'explode() expec...', '/in...', 57, Array) #1 /includes/pages/login/ShowIndexPage.class.php(57): explode('/n', Array) #2 /index.php(57): ShowIndexPage->show() #3 {main}

**Comment by jkroepke** [comment]
Thanks for the report.
