### ISSUE TITLE
Dark Matter Store

### ISSUE THREAD

**Issue by VidYen** [jkroepke/2Moons#359]
Hi thanks for the OAuth answer last time, but I have a second question I am helping them with...

Are there hooks for the Dark Matter system? That seems like what would be a cash shop kind of thing.

Basically I'd like check a json on another page and based on that (time and points they have), I'd like to add the dark matter to the user on the user table.

I could go in through php and do it, but I just want to ask before I do in case there was already a function to do this already written so didn't have to rewrite the wheel.

Thanks again!

-Felty

**Comment by jkroepke** [comment]
There is no store or something like that. You have to implement yourself.

**Comment by VidYen** [comment]
@jkroepke Ok. I'm familiar enough with PHP and SQL but I see you have your own function system made to communicate with the SQL DB.

I tried:

```php
		$sql	= 'UPDATE %%USERS%% SET `darkmatter` = :newTime WHERE `id` = :userId;';

		Database::get()->update($sql, array(
			':newTime'	=> 809,
			':userId'	=> 3
		));
```
But that didn't work. (I just tried a hard code to begin with for user 3 with setting darkmatter to 809.

running 
```sql
`UPDATE (userstable)_users SET `darkmatter` = 809 WHERE `id` = 3;`
```

works just fine.

**Comment by jkroepke** [comment]
Resources buildings or ship should be not updated directly inside users own session. Instead just set a new value inside the global vars `$USER`.

https://github.com/jkroepke/2Moons/blob/5709d7586df522ef92f965f36a372a2948b6f8f4/includes/pages/game/ShowBuildingsPage.class.php#L172

Yes, global vars. The concepts of the game/code are from 2006

**Comment by VidYen** [comment]
Ah thanks! I’m only 24 hours into your code and although I could just brute
force my way into the SQL server I know there is usually a proper way to
get in.

Does the user have a global variable for darkmatter than I can just add to
in php that would increase their total darkmatter holdings?

It doesn’t have to be in user session as I could have a cron job do the
curl and then update their balances.

I just need to know where the optimal place to do this automatically, if
possible.

**Comment by jkroepke** [comment]
`$USER[$resource[921]]` is the variable for dark matter.
https://github.com/jkroepke/2Moons/blob/15247f1b2677a196ad95d679070e54889af6b1ca/includes/vars.php#L28

**Comment by VidYen** [comment]
Thanks you I got it working via `if(isset($hash_balance)) { $USER[$resource[921]]		+= $hash_balance; }`

A lot easier than brute forcing the SQL tables. Thank you!
