### ISSUE TITLE
Adding Darkmatter to User based on Cronjob

### ISSUE THREAD

**Issue by VidYen** [jkroepke/2Moons#360]
Hi again! Hopefully this is last issue question for a while.

I was looking at the cronjob classes and saw that you already do what I want to do with curl `TrackingCronjob.class.php` and I have to ask

Is it possible to check to see if user has been logged in within the past 24 hours and if so give him a arbitrary sum of darkmatter?

And then run the cron job at 0 UTC time?

The arbitrary sum will be based on a curl on another website which I already have setup.

But as the user won't be logged into the cronjob php, I'm assuming the `if(isset($hash_balance)) { $USER[$resource[921]]		+= $hash_balance; }` unless we define the user in the cron job class?

Or can i use the global $USER and then set $USER['id'] manually?

On top of that, I'd need to get a list of the users and do a loop checking each their last login status.

So doing that... Whats the best way to get a list of all the users and their last login time in the cron php and then using the global variables to add DM to their accounts?

**Comment by jkroepke** [comment]
Look at the InactiveMailCronjob i check the last online time there.

You can do it with one sql query like `UPDATE users SET darkmatter = darkmatter + X WHERE onlinetime < time - 24h`

**Comment by VidYen** [comment]
Thank you! I got it working!
