### ISSUE TITLE
Error on the technologies page

### ISSUE THREAD

**Issue by korhaldragonir** [jkroepke/2Moons#73]
Hi,

I noticed that I get an error each time I try to open the Technologies page:

USER ERROR

Message: Unable to load template extends 'layout.full.tpl|page.techTree.default.tpl'
File: /includes/libs/Smarty/sysplugins/smarty_internal_template.php
Line: 219
URL: https://MASKED/2moons/game.php?page=techtree
PHP-Version: 5.5.9-1ubuntu4.13
PHP-API: apache2handler
MySQL-Cleint-Version: 5.5.44
2Moons Version: 1.7.2127
Debug Backtrace:
#0 /includes/libs/Smarty/Smarty.class.php(820): Smarty_Internal_Template->render(true, false, true)
 #1 /includes/libs/Smarty/Smarty.class.php(834): Smarty->fetch('extends:layout....', NULL, NULL, NULL, true)
 #2 /includes/classes/class.template.php(149): Smarty->display('extends:layout....')
 #3 /includes/pages/game/AbstractGamePage.class.php(260): template->display('extends:layout....')
 #4 /includes/pages/game/ShowTechtreePage.class.php(88): AbstractGamePage->display('page.techTree.d...')
 #5 /game.php(68): ShowTechtreePage->show()
 #6 {main}  

I don't have much experience with smarty so I am not sure where to look. Could you assist me or point me in the right direction. If I am able to fix it I will submit the patch.

Best Regards.

**Comment by jkroepke** [comment]
Hi.

what happens, if you clear the cache directory?

**Comment by korhaldragonir** [comment]
Hi,

After clearing the Cache the error still persists.

**Comment by Fansana** [comment]
this is an easy fix, you guys just have a typo in /includes/pages/game/ShowTechtreePage.class.php(88).
It calls something like TechTree and that is wrong!

**Comment by korhaldragonir** [comment]
Thanks that was it. Here is the patch that fixed it for me. http://pastebin.com/rEEK4ApY

**Comment by jkroepke** [comment]
Oh well. Hard to find this errors on windows machines!

**Comment by jkroepke** [comment]
Its fixed right now.

**Comment by korhaldragonir** [comment]
True, I only had this issue on my live server which runs Linux. Windows is not case sensitive so it does not occur.
