### ISSUE TITLE
Fleet distance

### ISSUE THREAD

**Issue by terassiel** [jkroepke/2Moons#76]
The function GetDistance() in flotten.js seem to be miscalculating the distance. Within the origin Galaxy the calculation is fine but if you jump into a new Galaxy the distance for each system and planet traveled does not get calculated. Meaning the time spend by each fleet stays the same whereever you travel within that galaxy.
function GetDistance() {
	var thisGalaxy = data.planet.galaxy;
	var thisSystem = data.planet.system;
	var thisPlanet = data.planet.planet;
	var targetGalaxy = document.getElementsByName("galaxy")[0].value;
	var targetSystem = document.getElementsByName("system")[0].value;
	var targetPlanet = document.getElementsByName("planet")[0].value;

	if (targetGalaxy - thisGalaxy != 0) {
		return Math.abs(targetGalaxy - thisGalaxy) * 20000;
	} else if (targetSystem - thisSystem != 0) {
		return Math.abs(targetSystem - thisSystem) * 5 * 19 + 2700;
	} else if (targetPlanet - thisPlanet != 0) {
		return Math.abs(targetPlanet - thisPlanet) * 5 + 1000;
	} else {
		return 5;
	}
}

Simply removing the "else" statemant does not work

**Comment by jkroepke** [comment]
Hi!

this is the expected result like in OGame it is. See: http://ogame.wikia.com/wiki/Distance
