### ISSUE TITLE
Disabling Admin Access does not seem to work.

### ISSUE THREAD

**Issue by korhaldragonir** [jkroepke/2Moons#77]
When clicking on the disable access link it does actually go away. However on each page refresh the banner shows up again. The only thing that will make it go away is logging out completely.  
  
How is this supposed to work? And in which file should I start my search.

Thanks in advance.

**Comment by jkroepke** [comment]
Hi!

Can you check, if commit b2ed478c57447ec8c9ea873afcca8bc2214e6d9b resolve your problem?

**Comment by korhaldragonir** [comment]
I just pulled in your master branch into my environment I will check it in a few moments and let you know.

**Comment by korhaldragonir** [comment]
You fixed it!

**Comment by jkroepke** [comment]
Thank you.
