### ISSUE TITLE
Construction time of buildings/fleet/defenses

### ISSUE THREAD

**Issue by terassiel** [jkroepke/2Moons#78]
My building time is showns as M:H:S where it should be H:M:S . Where can I change that? The Servertime does get shown in the correct order.

**Comment by jkroepke** [comment]
Hi!

Checkout commit 2ed264200d19d2d4d8f96a74587360bdc3b82a68

**Comment by jkroepke** [comment]
Reopen.

**Comment by jkroepke** [comment]
"The fix you proposed did not fix the whole issue. Next to the progress bar
it is still in the wrong order.", 

I can not verify this issue. The time next to the progress do not have any issues for me.

**Comment by terassiel** [comment]
The fix you proposed did put it in the right order in the building tabs (below the description of the building) but in the progress bar it is still in the wrong order.

**Comment by terassiel** [comment]
I cleared the cache and restarted building but for me the bug stays. Where is the order of the timestamp defined?

**Comment by jkroepke** [comment]
Here: https://github.com/jkroepke/2Moons/blob/2ed264200d19d2d4d8f96a74587360bdc3b82a68/includes/GeneralFunctions.php#L217

Anyway, look great for, not?

http://i.imgur.com/nuhOPog.png

**Comment by terassiel** [comment]
My code :
function pretty_time($seconds)
{
	global $LNG;
	
	$day	= floor($seconds / 86400);
	$hour	= floor($seconds / 3600 % 24);
	$minute	= floor($seconds / 60 % 60);
	$second	= floor($seconds % 60);

	$time  = '';

	if($day > 0) {
		$time .= sprintf('%d%s', $day, $LNG['short_day']);
	}

	return $time.sprintf('%02d%s %02d%s %02d%s',
		$hour, $LNG['short_hour'],
		$minute, $LNG['short_minute'],
		$second, $LNG['short_second']
	);
}

But as you can see next to the bar the minutes are still at the front.

![researchtime](https://cloud.githubusercontent.com/assets/15299574/10770219/5d886106-7cea-11e5-8088-a00c5cddf428.JPG)

**Comment by jkroepke** [comment]
Can I have access to your gane?

**Comment by jkroepke** [comment]
Your base.js looks different. Checkout this:

https://github.com/jkroepke/2Moons/blob/master/scripts/game/base.js#L120

**Comment by terassiel** [comment]
Thank you so much!
