### ISSUE TITLE
Disabling Modules does not hide Menu item

### ISSUE THREAD

**Issue by korhaldragonir** [jkroepke/2Moons#80]
When I disable a Module the Menu item in the game does not get hidden. Even after I clear the cache.

**Comment by jkroepke** [comment]
As an admin, you always see all modules even there are disabled.

**Comment by korhaldragonir** [comment]
True, but I have players that see the modules when they are on the overview page. Then once they click on the module they get the message inactive module. And they dissappear.

However if I go back to the Overview page the modules are visible again. So it apparantly works on all pages except for the Overview page.

**Comment by jkroepke** [comment]
It really looks like an cache problem, did you try to clear it again?

**Comment by korhaldragonir** [comment]
I will try it again. I will let you know.

**Comment by korhaldragonir** [comment]
I have tried clearing the cache again. But the issue still persists. Also it still ONLY occurs on the overview page. It is hidden on all other pages.

Might it have something to do with the OverviewPage template?

**Comment by jkroepke** [comment]
Hi!

Nope, it is like all other templates. Strang Issue again. I will try to reprocue it.

**Comment by korhaldragonir** [comment]
Hi Jan,

I think I found it. It appears to very persistent caching in my browser. I tested it on another computer that did not have any history of the game. And it works.

So it works exactly like you described. Thanks!

**Comment by jkroepke** [comment]
Thank your for your response!
