### ISSUE TITLE
Is it possible for players to get an e-mail when they have messages.

### ISSUE THREAD

**Issue by korhaldragonir** [jkroepke/2Moons#81]
One of my players asked if it is possible that he could get e-mails when for example his Construction fails. He does see the Messages in-game, but he would like to receive an e-mail about this.

A way to send out an hourly e-mail containing the aggregated messages might be a nice idea.

Any comments about this idea are welcome.

**Comment by Ignity** [comment]
How can a construction fail after you start it?

**Comment by korhaldragonir** [comment]
I am talking about the fact that you can queue up buildings. But the code will only check if you have the resources for the first one.

After that all sequential buildings can fail because either you do not or no longer have the required resources.

**Comment by OzanKurt** [comment]
This project has already ended and not being developed anymore. Please check 2moons.cc official forums. You can hire some developers for additional features.

**Comment by korhaldragonir** [comment]
Too bad. Seems I will have to do it myself then. Since I can hire some developers should I also charge for my translations then? How generous.......

**Comment by OzanKurt** [comment]
Sorry. :/

**Comment by jkroepke** [comment]
Uhm, i'm still there. The main developer.

**Comment by korhaldragonir** [comment]
Don't worry, Jan. Just because you are still working as hard as you are I will still submit the translations.

**Comment by jkroepke** [comment]
So, you want to talk about idea to implement this feature or not?

**Comment by OzanKurt** [comment]
If you wanna do it Jan, we can help I guess. 
At least I can...

One question:
How am i supposed to work with an installed local copy of the game?
Because installation deletes the `FIRST_INSTALL` file in `includes` directory. Should I simply `git checkout includes/FIRST_INSTALL`?

**Comment by korhaldragonir** [comment]
I am willing to assist as well as I can as well. But I will first have to read through the code a little. I already have SQL query which would return most of the info required for this feature.

**Comment by OzanKurt** [comment]
We should probably update our PhpMailer library too.

**Comment by jkroepke** [comment]
So I have two solutions:

- crontab:
run a crontab which runs all five minute to look for new messages and send mails.

- directly:
add a function directly to SendMessage function to send a mail. But aggregation where not possible here.

**Comment by korhaldragonir** [comment]
Both are fine solutions. I prefer the crontab one since that one does not require any interaction from the user side. And when having a lot of users you will have more control over the mail-flow. 

How do we plan keeping track of which messages a user has been notified about? Or are we going to send out an e-mail for as long as they are unread? 

E.g: A user gets the message he has unread messages, but is unable to login to check them today. Will he get another reminder the next day or not? And would we want that or not?

**Comment by OzanKurt** [comment]
It would be also cool if we could add a functionality to email which is responsible from logging in the user that received the email and clicked the link to check his buildings.

**Comment by korhaldragonir** [comment]
@OzanKurt you mean a link like;
   Some of your buildings were unable to construct. Click here to go to the queue

In which the Click here text is a link to the buildings page? That would be nice.

**Comment by korhaldragonir** [comment]
As promised this is the SQL query I built to get most of the information in one go:

``` SQL
SELECT 
  `uni1_users`.`username`, 
  `uni1_users`.`email`, 
  COUNT(`uni1_messages`.`message_subject`) AS `total` 
FROM 
  `uni1_messages` 
LEFT JOIN 
  `uni1_users` 
ON 
  `uni1_messages`.`message_owner` = `uni1_users`.`id` 
WHERE 
  `uni1_messages`.`message_subject` = 'Construction Failed!' 
GROUP BY 
  `uni1_messages`.`message_owner`;
```
Not sure if this is useful or not.

**Comment by Hilarious001** [comment]
Hello

This is quit simple

Way N1) You add a sendmail function in the planetresupdate file where it send you the message if the queu failed due to a lack of resource.

$to = $UserData['email'];
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
$headers .= 'From: no-reply@your_domain.com' . "\r\n";
$headers .= 'Reply-To: no-reply@your_domain.com' . "\r\n";
mail($to, $Subject, $Message, $headers);

Way N2)
If you want to do it with crontab, then you have to create a crontab file, and if you want to check if mail is already send, just add a row in the uni1_message called isMailSend (0,1)

And you select where the value is 0 and once mail is send you update it to 1.

Quit easy.

**Comment by penguin1969** [comment]
Speaking of..what happened to 2moons forum??

**Comment by jkroepke** [comment]
Hi,

I dont know. I'm not the maintainer of 2moons.cc.

penguin1969 <notifications@github.com> schrieb am Mo., 15. Feb. 2016, 06:11:

**Comment by penguin1969** [comment]
Well, if you talk to whomever is, I would be glad to help out by hosting it if that is the issue.

**Comment by bornhaeusser** [comment]
has somebody a working crontab file for sending in game messages to email?

**Comment by Hilarious001** [comment]
xD what the hell of function is that, first of all your cronjob will take age to get finished if you have a good amount of players. if alot of message are send

Just add this code in send message function

$Message = 'Mesage from game';
$to = $UserData['email'];
$headers = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
$headers .= 'From: no-reply@your_domain.com' . "\r\n";
$headers .= 'Reply-To: no-reply@your_domain.com' . "\r\n";
mail($to, $Subject, $Message, $headers);

**Comment by jkroepke** [comment]
You should not use php Mail function. Use the internal 2moons Mail function the prevent Spam flags. Sending mails should not taken more then 80ms...

Hilarious001 <notifications@github.com<mailto:notifications@github.com>> schrieb am Fr., 27. Mai 2016, 13:07:

xD what the hell of function is that, first of all your cronjob will take age to get finished if you have a good amount of players. if alot of message are send

Just add this code in send message function

$Message = 'Mesage from game';

$to = $UserData['email'];
$headers = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
$headers .= 'From: no-reply@your_domain.com<mailto:no-reply@your_domain.com>' . "\r\n";
$headers .= 'Reply-To: no-reply@your_domain.com<mailto:no-reply@your_domain.com>' . "\r\n";
mail($to, $Subject, $Message, $headers);

**Comment by bornhaeusser** [comment]
Ok i put the Text in the PlayerUtil.class.php after Line 656 in {}
I got an error that the Variable $UserDate is undef.

NOTICE: "Undefined variable: UserData"

Error LOG:

[27-May-2016 14:12:21] NOTICE: "Undefined variable: UserData"
File: /volume1/web/game/2moons/includes/classes/PlayerUtil.class.php | Line: 661
URL: http://db-cloud.de/game/2moons/game.php?page=overview | Version: 1.8.git
Stack trace:
#0 /includes/classes/PlayerUtil.class.php(661): errorHandler(8, 'Undefined varia...', '/volume1/web/ga...', 661, Array)
#1 /includes/classes/missions/MissionCaseSpy.class.php(161): PlayerUtil::sendMessage('1', 0, 'Spionageabteilu...', 0, 'Spionagebericht', '&lt;div class=&quot;spy...', '1464351140', NULL, 1, '1')
#2 /includes/classes/class.FlyingFleetHandler.php(80): MissionCaseSpy-&gt;TargetEvent()
#3 /includes/FleetHandler.php(31): FlyingFleetHandler-&gt;run()
#4 /includes/common.php(137): require('/volume1/web/ga...')
#5 /game.php(24): require('/volume1/web/ga...')
#6 {main}

**Comment by bornhaeusser** [comment]
// Start - Email Versand

        {
        
        $sql = "SELECT email FROM uni1_users WHERE id = :userId;";
        
        $Message = 'Mesage from db space game';
         $to = $sql;
        $headers = 'MIME-Version: 1.0' . "\r\n";
        $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
        $headers .= 'From: xxx@xxx<mailto:space@xxx.de>' . "\r\n";
        $headers .= 'Reply-To: xxx@xxx.de<mailto:xxxx@xxxx.de>' . "\r\n";
        Mail::send($to, $subject, $Message, $headers);
        }
        
// Ende - Emailversand 


NOTICE: "Undefined variable: userID"

**Comment by Hilarious001** [comment]
the code works but you have to adapt it for your game and you didnt define :userId
jan said above its better to use 2moons internal function

mail::MultiSend or something like that

**Comment by bornhaeusser** [comment]
no i get the id but the Variable is filled wrong in my case:

require 'includes/classes/Mail.class.php';
        
        $sql = "SELECT email FROM uni1_users WHERE id = $userId";
    
        
        $Message = 'Message from db space game';
         $to = $sql;
        $headers = 'MIME-Version: 1.0' . "\r\n";
        $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
        $headers .= 'From: space@xxx.de<mailto:space@xxx.de>' . "\r\n";
        $headers .= 'Reply-To: space@xxx.de<mailto:space@xxx.de>' . "\r\n";
        mail::send($to, $subject, $Message, $headers); 


[27-May-2016 21:19:36] USER ERROR: "Invalid address: SELECT email FROM uni1_users WHERE id = 5"

**Comment by bornhaeusser** [comment]
Solution:

Add after Line 156 in UserUtility.class.php:

// Start - Email Versand

   $db = Database::get();    

        $sql = "SELECT * FROM  %%USERS%% WHERE id = :id;";
    
        $to = $db->selectSingle($sql, array(
        ':id' => $userId
        ));
        
		$Message = $text;
        $headers = 'MIME-Version: 1.0' . "\r\n";
        $headers .= 'Content-type: text/html; charset=utf-8' . "\r\n";
        $headers .= 'From: space@db-cloud.de' . "\r\n";
        $headers .= 'Reply-To: space@db-cloud.de' . "\r\n";
		if($to['spyMessagesMode'] == 1)
		{
		mail($to['email'], $subject, $Message, $headers); 
		}
// Ende - Emailversand	

This little snip does send Emails to the User if compact Spy Messages in the Settings is activ.
If you don´t like to have a setting then you can use this:

// Start - Email Versand

   $db = Database::get();    

        $sql = "SELECT * FROM  %%USERS%% WHERE id = :id;";
    
        $to = $db->selectSingle($sql, array(
        ':id' => $userId
        ));
        
		$Message = $text;
        $headers = 'MIME-Version: 1.0' . "\r\n";
        $headers .= 'Content-type: text/html; charset=utf-8' . "\r\n";
        $headers .= 'From: space@db-cloud.de' . "\r\n";
        $headers .= 'Reply-To: space@db-cloud.de' . "\r\n";
        mail($to['email'], $subject, $Message, $headers); 

// Ende - Emailversand

**Comment by jkroepke** [comment]
I will not implement this feature, because it require sql changes. Thats what I dont want anymore.

Anyway, the solutions above maybe works. Improved code:

```
$sql = "SELECT username, email FROM  %%USERS%% WHERE id = :id;";

$to = $db->selectSingle($sql, array(
    ':id' => $userId
));

require 'includes/classes/Mail.class.php';
Mail::send($to['email'], $to['username'], $subject, $text);
```

Never use mail(), because it ignore all mail settings that can be configured in the admin panel.
Also `SELECT * FORM` is bad, too.

The next step would be an Template like

```
Hello!

here is a new message for you:

{MESSAGE}

Cheers,
Your Game
```

saved in `languages/<code>/templates/pn.txt`

Then you can do things like
```
$text = str_replace('{MESSAGE}', $text, $LNG->getTemplate('pn');
```
The mails will be look more awesome like in the solution before.

**Comment by bornhaeusser** [comment]
Changed to:

`$db = Database::get();    
        $sql = "SELECT username, email FROM  %%USERS%% WHERE id = :id;";
		$to = $db->selectSingle($sql, array(
		 		':id' => $userId
				));
        $subject2 = 'IGM from: ' . $senderName . ' - ' . $subject;
		$Message = $text;
        $headers = 'MIME-Version: 1.0' . "\r\n";
        $headers .= 'Content-type: text/html; charset=utf-8' . "\r\n";
        $headers .= 'From: space@db-cloud.de' . "\r\n";
        $headers .= 'Reply-To: space@db-cloud.de' . "\r\n";
		mail($to['email'], $subject2, $Message, $headers); `

got an error:

Fatal error: Cannot redeclare class Mail in /2moons/includes/classes/Mail.class.php on line 21

**Comment by jkroepke** [comment]
Use require_once

bornhaeusser <notifications@github.com<mailto:notifications@github.com>> schrieb am Do., 9. Juni 2016, 19:51:

Changed to:

$db = Database::get();
$sql = "SELECT username, email FROM %%USERS%% WHERE id = :id;";

$to = $db->selectSingle($sql, array(
':id' => $userId
));

$subject2 = 'IGM from: ' . $senderName . ' - ' . $subject;

$Message = $text;
$headers = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=utf-8' . "\r\n";
$headers .= 'From: space@db-cloud.de<mailto:space@db-cloud.de>' . "\r\n";
$headers .= 'Reply-To: space@db-cloud.de<mailto:space@db-cloud.de>' . "\r\n";

mail($to['email'], $subject2, $Message, $headers);

got an error:

Fatal error: Cannot redeclare class Mail in /2moons/includes/classes/Mail.class.php on line 21

**Comment by bornhaeusser** [comment]
That works - but i receive a Mail wich look s terrible:

<div class="spyRaport"> <div class="spyRaportHead"> <a href="game.php?page=galaxy&amp;galaxy=1&amp;system=3">Spionagebericht von Hauptplanet [1:3:7] am 09. Jun 2016, 21:07:49</a> </div> <div class="spyRaportContainer"> <div class="spyRaportContainerHead spyRaportContainerHeadClass900">Rohstoffe</div> <div class="spyRaportContainerRow clearfix"> <div class="spyRaportContainerCell">Metall</div> <div class="spyRaportContainerCell">1.315</div> <div class="spyRaportContainerCell">Kristall</div> <div class="spyRaportContainerCell">665</div> </div> <div class="spyRaportContainerRow clearfix"> <div class="spyRaportContainerCell">Energie</div> <div class="spyRaportContainerCell">22</div> </div> <div class="spyRaportContainer"> <div class="spyRaportContainerHead spyRaportContainerHeadClass200">Schiffe</div> </div> <div class="spyRaportContainer"> <div class="spyRaportContainerHead spyRaportContainerHeadClass400">Verteidigungsanlagen</div> </div> <div class="spyRaportContainer"> <div class="spyRaportContainerHead spyRaportContainerHeadClass0">Gebäude</div> <div class="spyRaportContainerRow clearfix"> <div class="spyRaportContainerCell">Solarkraftwerk</div> <div class="spyRaportContainerCell">1</div> </div> <div class="spyRaportContainer"> <div class="spyRaportContainerHead spyRaportContainerHeadClass100">Forschungen</div> </div> <div class="spyRaportFooter"> <a href="game.php?page=fleetTable&amp;galaxy=1&amp;system=3&amp;planet=7&amp;planettype=1&amp;target_mission=1">Angreifen</a> <br>Die Wahrscheinlichkeit der Zerstörung der Spionagesonde beträgt: 0 % 		<br><a href="game.php?page=battleSimulator&amp;im[901]=1314.7914935556&amp;im[902]=665.44262177778&amp;im[911]=22&amp;im[4]=1">Simulieren</a> </div> </div>
