### ISSUE TITLE
Moon destruction

### ISSUE THREAD

**Issue by terassiel** [jkroepke/2Moons#82]
Using a fresh copy of the MissionCaseDestruction.class the moon was not deleted from the DB. The battlereport gave a positiv outcome, but the moon is still active afterwards.

**Comment by jkroepke** [comment]
Hi!

please just one problem/bug in any issue ticket here.

**Comment by terassiel** [comment]
Could in the missionCaseDestruction this line be changeg into a direct sql query?
(line 405)

PlayerUtil::deletePlanet($targetPlanet['id']);

**Comment by jkroepke** [comment]
Fixed in ef63d73355ca3415de14be78d8b61e5fe3d8faef
