### ISSUE TITLE
Would you consider using composer for Smarty?

### ISSUE THREAD

**Issue by OzanKurt** [jkroepke/2Moons#84]
Would you consider using composer for Smarty?

**Comment by jkroepke** [comment]
Today yes. 

But also I would choose a another template engine, for example twig.

Anyway, I do not see the advantage for this project to using composer.

**Comment by OzanKurt** [comment]
You're right, all would take so much time. 

But still, we could add some little tweaks like:
- filp/whoops
- raveren/kint
- maximebf/debugbar

 I just realised that all of there are for development purposes. :package: :smile:

**Comment by jkroepke** [comment]
Pretty awsome projects!

Any yes, it is only usefull for developers. So my IDE can handle composer as well. 

For production use, I could only use it for smarty and it this would not be very usefull. Not?

**Comment by OzanKurt** [comment]
Yes, it would just save you a bit of space from github repo. :smiley: 
We can still add some stuff to improve the system.

Maybe:
- `illuminate/hashing`
This package will remove the unsecure `md5()` from `PlayerUtils` class.
- and of course `illuminate/container` to hold the all the packages we may add in one piece.

This way we could extend our Abstract pages to an `Application` class which will hold the instance of `illuminate/container` which actually holds all required classes instances inside and let us use them anywhere we want.

After extending the `Application` class it would be something like this to use the packages.
```php
class ShowLoginPage extends AbstractClass {
    ...
    function show() {
        ...
        $this->app->hasher->check($userInputPassword, $USER['password']);
        ...
    }
    ...
}
```

:smile: I am thinking about this thing for months.

**Comment by jkroepke** [comment]
Hi,

md5 hashsum is only use for convert passwords after upgrade to 1.7 Normally, bcrypt is used, which is secure enough. :)

**Comment by OzanKurt** [comment]
Yes. :) If anything you have in mind to develop or improve the current release plase don't hesitate sharing your ideas with me so can contribute as much as possible.
