### ISSUE TITLE
Chat ohne Funktion 1.8.git

### ISSUE THREAD

**Issue by Casiopajer** [jkroepke/2Moons#87]
Der Chat ist ohne Funktion. Habe ihn bis auf weiteres Deaktiviert.

**Comment by jkroepke** [comment]
Hi,

wie im Forum schon geschrieben, sollte ca1b986bff2711ea775e6a014db677d1f018966c den Chat wieder funktionsfähig machen.

**Comment by Casiopajer** [comment]
Hat bestens geklappt, Danke
