### ISSUE TITLE
Neues Problem, mit Cronjob

### ISSUE THREAD

**Issue by Casiopajer** [jkroepke/2Moons#88]
[01-Nov-2015 18:14:58] WARNING: "Invalid argument supplied for foreach()"
File: /var/www/vhosts/euve84066.serverprofi24.de/httpdocs/includes/classes/class.statbuilder.php | Line: 77
URL: euve84066.serverprofi24.de/cronjob.php?cronjobID=2 | Version: 1.8.git
Stack trace:
#0 /includes/classes/class.statbuilder.php(77): errorHandler(2, 'Invalid argumen...', '/var/www/vhosts...', 77, Array)
#1 /includes/classes/class.statbuilder.php(290): statbuilder-&gt;GetUsersInfosFromDB()
#2 /includes/classes/cronjob/StatisticCronjob.class.php(38): statbuilder-&gt;MakeStats()
#3 /includes/classes/Cronjob.class.php(68): StatisticCronjob-&gt;run()
#4 /cronjob.php(65): Cronjob::execute(2)
#5 {main}

**Comment by jkroepke** [comment]
Komisch.

$reslist['build'] kommt von den vars. Kannst du mal deinen Cache leeren?

**Comment by OzanKurt** [comment]
Hab eine frage, wie wird diese cronjobs "triggered". #deutsch

**Comment by Casiopajer** [comment]
War wohl ein problem mit dem update der Chatdatein. Cache löschen brachte nix. Nach kompletter Neu Instalation geht nun alles.

**Comment by Casiopajer** [comment]
Fehler ist wieder da auch nach Neuinstalation.

[02-Nov-2015 19:00:55] WARNING: "Invalid argument supplied for foreach()"
File: /var/www/vhosts/worldwargame.de/httpdocs/includes/classes/class.statbuilder.php | Line: 77
URL: http://www.worldwargame.de/cronjob.php?cronjobID=2 | Version: 1.8.git
Stack trace:
#0 /includes/classes/class.statbuilder.php(77): errorHandler(2, 'Invalid argumen...', '/var/www/vhosts...', 77, Array)
#1 /includes/classes/class.statbuilder.php(290): statbuilder-&gt;GetUsersInfosFromDB()
#2 /includes/classes/cronjob/StatisticCronjob.class.php(38): statbuilder-&gt;MakeStats()
#3 /includes/classes/Cronjob.class.php(68): StatisticCronjob-&gt;run()
#4 /cronjob.php(65): Cronjob::execute(2)
#5 {main}

**Comment by Casiopajer** [comment]
Registrieren neuer Spieler auch nicht mehr möglich.

Debug Backtrace:
#0 /includes/classes/PlayerUtil.class.php(165): errorHandler(8, 'Undefined index...', 'FILEPATH ...', 165, Array)
#1 /includes/pages/login/ShowVertifyPage.class.php(72): PlayerUtil::createPlayer('1', 'Casandro', '$2a$09$ybkaGvQq...', 'moellerdaniel@t...', 'de')
#2 /includes/pages/login/ShowVertifyPage.class.php(140): ShowVertifyPage->_activeUser()
#3 /index.php(68): ShowVertifyPage->show()
#4 {main}

**Comment by jkroepke** [comment]
Moin,

bitte nur ein Problem pro Ticket.

**Comment by Casiopajer** [comment]
ok soll ich jetzt ein neues machen oder ist es diesmal ok?

**Comment by jkroepke** [comment]
Neues.

**Comment by Hilarious001** [comment]
i have the same problem
When i call ids manualy with an array instead of the reslist code its pass trough it but i get then the error for the next reslist['tech'] so i get it for all $reslist in the statbuilder page for pdo version

**Comment by jkroepke** [comment]
Hi!

Can I have a database dump? You can send it to my address here.

Please anonymize user and passwords.

**Comment by Hilarious001** [comment]
jan you should close this :P
