### ISSUE TITLE
Jump Gate shows no targets

### ISSUE THREAD

**Issue by terassiel** [jkroepke/2Moons#89]
The Jumpgate shows no target Jumpgates. It doesnt matter if the jumpgates are in the same galaxy or not, no possible target gates are shown.
All files with the latest changes, no custom changes. Error log shows nothing.

**Comment by terassiel** [comment]
I fixed it and added a reduction for the recharge time.

**Comment by jkroepke** [comment]
Thanks, I got your mail.

**Comment by jkroepke** [comment]
I will close it, if the patch is applyed.

**Comment by Hilarious001** [comment]
I fixed the appaerence of the jumpgate but when i try to jump i get this error

Message: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

Query-Code:UPDATE uni1_planets SET big_ship_cargo = big_ship_cargo - 2, light_hunter = light_hunter - 100, last_jump_time = 1450920278 WHERE id = 25;

**Comment by OzanKurt** [comment]
It's about the PDO parameter bindings. Can you please provide the code?

**Comment by jkroepke** [comment]
See here: https://github.com/jkroepke/2Moons/blob/master/includes/pages/game/ShowInformationPage.class.php#L118

Problem is that the subquery is a PDO parameter. This is wrong here. It must be like here: https://github.com/jkroepke/2Moons/blob/560c52f30250c72d52e1e327598712772e5be8ce/includes/classes/class.PlanetRessUpdate.php#L709
