### ISSUE TITLE
HOF

### ISSUE THREAD

**Issue by terassiel** [jkroepke/2Moons#93]
The HOF does not give the right place ranks. They are correctly sorted by shot units but the ranks make no sense.
![hof](https://cloud.githubusercontent.com/assets/15299574/10964886/013c5bac-83aa-11e5-9d2e-caea02df80fb.JPG)

**Comment by terassiel** [comment]
Fixed it, error originated from a corrupt update.

**Comment by Hilarious001** [comment]
Terassiel, can you close this then as its not a 2moons error, so jan can see easily whats still to fix and other contrib can see it to
